#include <std_include.hpp>
#include "zonetool/iw6/converter/h1/include.hpp"
#include "vehicledef.hpp"

#include "zonetool/h1/assets/vehicledef.hpp"

#include "zonetool/iw6/functions.hpp"

namespace zonetool::iw6
{
	namespace converter::h1
	{
		namespace vehicledef
		{
			zonetool::h1::VehicleDef* convert(VehicleDef* asset, utils::memory::allocator& allocator)
			{
				const auto new_asset = allocator.allocate<zonetool::h1::VehicleDef>();

				COPY_VALUE(name);
				COPY_VALUE_CAST(type);
				COPY_VALUE(useHintString);
				COPY_VALUE(health);
				COPY_VALUE(quadBarrel);
				COPY_VALUE(hitClientScriptables);
				new_asset->multipleLinkedGroundEntities = 0;
				new_asset->hideVehicleForDriver = 0;
				COPY_VALUE(texScrollScale);
				COPY_VALUE(topSpeed);
				COPY_VALUE(accel);
				COPY_VALUE(rotRate);
				COPY_VALUE(rotAccel);
				COPY_VALUE(maxBodyPitch);
				COPY_VALUE(maxBodyRoll);
				new_asset->legIK = 0;
				COPY_VALUE(fakeBodyAccelPitch);
				COPY_VALUE(fakeBodyAccelRoll);
				COPY_VALUE(fakeBodyVelPitch);
				COPY_VALUE(fakeBodyVelRoll);
				COPY_VALUE(fakeBodySideVelPitch);
				COPY_VALUE(fakeBodyPitchStrength);
				COPY_VALUE(fakeBodyRollStrength);
				COPY_VALUE(fakeBodyPitchDampening);
				COPY_VALUE(fakeBodyRollDampening);
				COPY_VALUE(fakeBodyBoatRockingAmplitude);
				COPY_VALUE(fakeBodyBoatRockingPeriod);
				COPY_VALUE(fakeBodyBoatRockingRotationPeriod);
				COPY_VALUE(fakeBodyBoatRockingFadeoutSpeed);
				COPY_VALUE(boatBouncingMinForce);
				COPY_VALUE(boatBouncingMaxForce);
				COPY_VALUE(boatBouncingRate);
				COPY_VALUE(boatBouncingFadeinSpeed);
				COPY_VALUE(boatBouncingFadeoutSteeringAngle);
				COPY_VALUE(collisionDamage);
				COPY_VALUE(collisionSpeed);
				COPY_ARR(killcamOffset);
				COPY_VALUE(playerProtected);
				COPY_VALUE(bulletDamage);
				COPY_VALUE(armorPiercingDamage);
				COPY_VALUE(grenadeDamage);
				COPY_VALUE(projectileDamage);
				COPY_VALUE(projectileSplashDamage);
				COPY_VALUE(heavyExplosiveDamage);
				new_asset->pad1 = 0;
				COPY_VALUE(vehPhysDef.physicsEnabled);
				COPY_VALUE(vehPhysDef.physPresetName);
				COPY_VALUE_CAST(vehPhysDef.physPreset);
				new_asset->vehPhysDef.physMassName = nullptr;
				new_asset->vehPhysDef.physMass = nullptr;
				COPY_VALUE(vehPhysDef.accelGraphName);
				COPY_VALUE_CAST(vehPhysDef.steeringAxle);
				COPY_VALUE_CAST(vehPhysDef.powerAxle);
				COPY_VALUE_CAST(vehPhysDef.brakingAxle);
				COPY_VALUE(vehPhysDef.topSpeed);
				new_asset->vehPhysDef.topSpeedTurbo = 0.f;
				COPY_VALUE(vehPhysDef.reverseSpeed);
				COPY_VALUE(vehPhysDef.maxVelocity);
				COPY_VALUE(vehPhysDef.maxPitch);
				COPY_VALUE(vehPhysDef.maxRoll);
				new_asset->vehPhysDef.wheelRadius = 0.f;
				COPY_VALUE(vehPhysDef.suspensionTravelFront);
				COPY_VALUE(vehPhysDef.suspensionTravelRear);
				COPY_VALUE(vehPhysDef.suspensionStrengthFront);
				COPY_VALUE(vehPhysDef.suspensionDampingFront);
				COPY_VALUE(vehPhysDef.suspensionStrengthRear);
				COPY_VALUE(vehPhysDef.suspensionDampingRear);
				COPY_VALUE(vehPhysDef.frictionBraking);
				COPY_VALUE(vehPhysDef.frictionCoasting);
				COPY_VALUE(vehPhysDef.frictionTopSpeed);
				COPY_VALUE(vehPhysDef.frictionSide);
				COPY_VALUE(vehPhysDef.frictionSideRear);
				new_asset->vehPhysDef.handBrakeLongitudinalSteerableFrictionScale = 0.f;
				new_asset->vehPhysDef.handBrakeLateralSteerableFrictionScale = 0.f;
				new_asset->vehPhysDef.handBrakeLongitudinalNonsteerableFrictionScale = 0.f;
				new_asset->vehPhysDef.handBrakeLateralNonsteerableFrictionScale = 0.f;
				new_asset->vehPhysDef.handBrakingStrength = 0.f;
				new_asset->vehPhysDef.handBrakeExtraYawTorque = 0.f;
				new_asset->vehPhysDef.speedAtMaxHandBrakeExtraYawTorque = 0.f;
				new_asset->vehPhysDef.driveForceFalloffFraction = 0.f;
				COPY_VALUE(vehPhysDef.velocityDependentSlip);
				COPY_VALUE(vehPhysDef.rollStability);
				COPY_VALUE(vehPhysDef.rollResistance);
				COPY_VALUE(vehPhysDef.pitchResistance);
				COPY_VALUE(vehPhysDef.yawResistance);
				COPY_VALUE(vehPhysDef.uprightStrengthPitch);
				COPY_VALUE(vehPhysDef.uprightStrengthRoll);
				COPY_VALUE(vehPhysDef.targetAirPitch);
				COPY_VALUE(vehPhysDef.airYawTorque);
				COPY_VALUE(vehPhysDef.airPitchTorque);
				COPY_VALUE(vehPhysDef.minimumMomentumForCollision);
				COPY_VALUE(vehPhysDef.collisionLaunchForceScale);
				COPY_VALUE(vehPhysDef.wreckedMassScale);
				COPY_VALUE(vehPhysDef.wreckedBodyFriction);
				COPY_VALUE(vehPhysDef.minimumJoltForNotify);
				COPY_VALUE(vehPhysDef.slipThresholdFront);
				COPY_VALUE(vehPhysDef.slipThresholdRear);
				COPY_VALUE(vehPhysDef.slipFricScaleFront);
				COPY_VALUE(vehPhysDef.slipFricScaleRear);
				COPY_VALUE(vehPhysDef.slipFricRateFront);
				COPY_VALUE(vehPhysDef.slipFricRateRear);
				COPY_VALUE(vehPhysDef.slipYawTorque);
				new_asset->vehPhysDef.cruiseControlProportionalGain = 0.f;
				new_asset->vehPhysDef.cruiseControlIntegralGain = 0.f;
				COPY_VALUE(boostDuration);
				COPY_VALUE(boostRechargeTime);
				COPY_VALUE(boostAcceleration);
				new_asset->boostTopSpeed = 0.f;
				COPY_VALUE(suspensionTravel);
				COPY_VALUE(maxSteeringAngle);
				COPY_VALUE(steeringLerp);
				new_asset->steeringLerpCentering = 0.f;
				COPY_VALUE(minSteeringScale);
				COPY_VALUE(minSteeringSpeed);
				new_asset->disableWheelsTurning = 0;
				new_asset->pad2 = 0.f;
				new_asset->treadDefaultFx = nullptr;
				new_asset->handBrakeDefaultFx = nullptr;
				new_asset->handBrakeLeftFx = nullptr;
				new_asset->handBrakeRightFx = nullptr;
				new_asset->boostFx = nullptr;
				new_asset->treadFxSlowestRepeatRate = 0.f;
				new_asset->treadFxFastestRepeatRate = 0.f;
				new_asset->treadFxMinSpeed = 0.f;
				new_asset->treadFxMaxSpeed = 0.f;
				COPY_VALUE(vehHelicopterIsASplinePlane);
				new_asset->vehHelicopterOrbitsAroundPoint = 0;
				COPY_VALUE(vehHelicopterLockAltitude);
				COPY_VALUE(vehHelicopterOffsetFromMesh);
				COPY_VALUE(vehHelicopterAltitudeOffset);
				COPY_VALUE(vehHelicopterPitchOffset);
				COPY_VALUE(vehHelicopterBoundsRadius);
				new_asset->vehHelicopterBoundsOffsetZ = 0.f;
				COPY_VALUE(vehHelicopterMaxSpeed);
				COPY_VALUE(vehHelicopterMaxSpeedVertical);
				COPY_VALUE(vehHelicopterMaxAccel);
				COPY_VALUE(vehHelicopterMaxAccelVertical);
				COPY_VALUE(vehHelicopterDecelerationFwd);
				COPY_VALUE(vehHelicopterDecelerationSide);
				COPY_VALUE(vehHelicopterDecelerationUp);
				COPY_VALUE(vehHelicopterMaxYawRate);
				COPY_VALUE(vehHelicopterMaxYawAccel);
				COPY_VALUE(vehHelicopterTiltFromVelocity);
				COPY_VALUE(vehHelicopterTiltFromControllerAxes);
				COPY_VALUE(vehHelicopterTiltFromAcceleration);
				COPY_VALUE(vehHelicopterTiltFromDeceleration);
				COPY_VALUE(vehHelicopterTiltFromFwdAndYaw_VelAtMaxTilt);
				COPY_VALUE(vehHelicopterTiltFromFwdAndYaw);
				COPY_VALUE(vehHelicopterTiltMomentum);
				COPY_VALUE(vehHelicopterTiltSpeed);
				COPY_VALUE(vehHelicopterMaxPitch);
				COPY_VALUE(vehHelicopterMaxRoll);
				COPY_VALUE(vehHelicopterHoverSpeedThreshold);
				COPY_VALUE(vehHelicopterJitterJerkyness);
				new_asset->vehHelicopterUseHoverWobble = 0;
				new_asset->vehHelicopterHoverWobblePhase = 0.f;
				new_asset->vehHelicopterHoverWobbleAmplitude = 0.f;
				new_asset->vehHelicopterUseBob = 0;
				new_asset->vehHelicopterBobPhase = 0.f;
				new_asset->vehHelicopterBobAmplitude = 0.f;
				COPY_VALUE(vehHelicopterLookaheadTime);
				COPY_VALUE(vehHelicopterSoftCollisions);
				COPY_VALUE(vehHelicopterUseGroundFX);
				COPY_VALUE_CAST(vehHelicopterGroundFx);
				COPY_VALUE_CAST(vehHelicopterGroundWaterFx);
				COPY_VALUE(vehHelicopterGroundFxDefaultRepeatRate);
				COPY_VALUE(vehHelicopterGroundFxSlowestRepeatRate);
				COPY_VALUE(vehHelicopterGroundFxFastestRepeatRate);
				COPY_VALUE(vehHelicopterGroundFxMinGroundDist);
				COPY_VALUE(vehHelicopterGroundFxMaxGroundDist);
				COPY_VALUE(vehSplinePlaneCorridorMaxXVel);
				COPY_VALUE(vehSplinePlaneCorridorMaxZVel);
				COPY_VALUE(vehSplinePlaneCorridorMaxXAccel);
				COPY_VALUE(vehSplinePlaneCorridorMaxZAccel);
				COPY_VALUE(vehSplinePlaneTangentLookAtRate);
				COPY_VALUE(vehSplinePlaneMaxPitchSpeed);
				COPY_VALUE(vehSplinePlaneMaxYawSpeed);
				COPY_VALUE(vehSplinePlaneMaxRollSpeed);
				COPY_VALUE(vehSplinePlanePitchSpeedRate);
				COPY_VALUE(vehSplinePlaneYawSpeedRate);
				COPY_VALUE(vehSplinePlaneRollSpeedRateUp);
				COPY_VALUE(vehSplinePlaneRollSpeedRateDown);
				COPY_VALUE(vehSplinePlaneMaxPitchAccel);
				COPY_VALUE(vehSplinePlaneMaxYawAccel);
				COPY_VALUE(vehSplinePlaneMaxRollAccel);
				COPY_VALUE(vehSplinePlaneYawToRollFactor);
				COPY_VALUE(vehSplinePlaneRollToYawFactor);
				COPY_VALUE(vehSplinePlaneRollToYawFactorBlend);
				COPY_VALUE(vehSplinePlaneMaxPitch);
				COPY_VALUE(vehSplinePlaneMaxRoll);
				COPY_VALUE(vehSplinePlaneMaxPitchFromRoll);
				COPY_VALUE(vehSplinePlaneMaxRollYawOffset);
				COPY_VALUE(vehSplinePlaneRollYawOffsetThreshold);
				COPY_VALUE(vehSplinePlaneMaxTiltRoll);
				COPY_VALUE(vehSplinePlaneMaxTiltPitch);
				COPY_VALUE(vehSplinePlaneTiltRollRate);
				COPY_VALUE(vehSplinePlaneTiltPitchRate);
				new_asset->vehJetbikeThrottleForce = 0.f;
				new_asset->vehJetbikeStrafeForce = 0.f;
				new_asset->vehJetbikeYawTorque = 0.f;
				new_asset->vehJetbikePitchTorque = 0.f;
				new_asset->vehJetbikeYawDamping = 0.f;
				new_asset->vehJetbikePitchDamping = 0.f;
				new_asset->vehJetbikeRollDamping = 0.f;
				new_asset->vehJetbikeRepulsorMaxForceFraction = 0.f;
				new_asset->vehJetbikeRepulsorMinForceFraction = 0.f;
				new_asset->vehJetbikeRepulsorCompressionDampingConstant = 0.f;
				new_asset->vehJetbikeRepulsorReboundDampingConstant = 0.f;
				new_asset->vehJetbikeRepulsorTorqueScale = 0.f;
				new_asset->vehJetbikeRepulsorCrossCoupling = 0.f;
				new_asset->vehJetbikeAntislipConstant = 0.f;
				new_asset->vehJetbikeAntislipMaxForce = 0.f;
				new_asset->vehJetbikeControlForceLocalOffsetX = 0.f;
				new_asset->vehJetbikeControlForceLocalOffsetZ = 0.f;
				new_asset->vehJetbikeControlTorqueLocalOffsetX = 0.f;
				new_asset->vehJetbikeControlTorqueLocalOffsetZ = 0.f;
				new_asset->vehJetbikeMaxControlForce = 0.f;
				new_asset->vehJetbikeMinContactForFullControl = 0.f;
				new_asset->vehJetbikeThrustScaleWithNoContact = 0.f;
				new_asset->vehJetbikeTorqueScaleWithNoContact = 0.f;
				new_asset->vehJetbikeUprightingTorque = 0.f;
				new_asset->vehJetbikeUprightingTorqueWithNoContact = 0.f;
				new_asset->vehJetbikeWeathervaneTorque = 0.f;
				new_asset->vehJetbikeWeathervaneTorqueWithNoContact = 0.f;
				new_asset->vehJetbikeAiSteeringConstant = 0.f;
				new_asset->vehJetbikeAiStationarySteeringScale = 0.f;
				new_asset->vehJetbikeAiThrottleConstant = 0.f;
				new_asset->vehHovertankAutoYawForce = 0.f;
				new_asset->vehHovertankAutoBrakeForce = 0.f;
				new_asset->vehHovertankRandomHoverForceMagMin = 0.f;
				new_asset->vehHovertankRandomHoverForceMagMax = 0.f;
				new_asset->vehHovertankRandomHoverForceStartTimerMin = 0.f;
				new_asset->vehHovertankRandomHoverForceStartTimerMax = 0.f;
				new_asset->vehHovertankRandomHoverForceDurationMin = 0.f;
				new_asset->vehHovertankRandomHoverForceDurationMax = 0.f;
				new_asset->vehDiveboatInitialDiveForceFactor = 0.f;
				new_asset->vehDiveboatContinuingDiveForceFactor = 0.f;
				new_asset->vehDiveboatMaxDiveTime = 0.f;
				new_asset->vehDiveboatDiveResetTime = 0.f;
				new_asset->vehDiveboatSubmergedDragFactor = 0.f;
				new_asset->vehDiveboatRollFactor = 0.f;
				new_asset->vehDiveboatBuoyancyOffset = 0.f;
				new_asset->pad3 = 0.f;
				new_asset->vehDiveboatSteeringGraphName = nullptr;
				new_asset->steeringGraphIndex = 0;
				new_asset->vehOrbiterMinYaw = 0.f;
				new_asset->vehOrbiterMaxYaw = 0.f;
				new_asset->vehOrbiterMinZ = 0.f;
				new_asset->vehOrbiterMaxZ = 0.f;
				new_asset->vehOrbiterAngularAcceleration = 0.f;
				new_asset->vehOrbiterAngularMaxVelocity = 0.f;
				new_asset->vehOrbiterAngularDeceleration = 0.f;
				new_asset->vehOrbiterAngularADSDeceleration = 0.f;
				new_asset->vehOrbiterAngularBraking = 0.f;
				new_asset->vehOrbiterAngularADSBraking = 0.f;
				new_asset->vehOrbiterAngularLookAheadTime = 0.f;
				new_asset->vehOrbiterVerticalAcceleration = 0.f;
				new_asset->vehOrbiterVerticalMaxVelocity = 0.f;
				new_asset->vehOrbiterVerticalDeceleration = 0.f;
				new_asset->vehOrbiterVerticalADSDeceleration = 0.f;
				new_asset->vehOrbiterVerticalBraking = 0.f;
				new_asset->vehOrbiterVerticalADSBraking = 0.f;
				new_asset->vehOrbiterVerticalLookAheadTime = 0.f;
				new_asset->vehOrbiterADSVelocityMult = 0.f;
				new_asset->vehOrbiterTiltRollMax = 0.f;
				new_asset->vehOrbiterTiltRollRate = 0.f;
				new_asset->vehOrbiterTiltPitchMax = 0.f;
				new_asset->vehOrbiterTiltPitchRate = 0.f;
				COPY_VALUE(camLookEnabled);
				COPY_VALUE(camRelativeControl);
				COPY_VALUE(camRemoteDrive);
				COPY_VALUE(camLerp);
				COPY_VALUE(camHeight);
				COPY_VALUE(camRadius);
				COPY_VALUE(camPitchInfluence);
				COPY_VALUE(camYawInfluence);
				COPY_VALUE(camRollInfluence);
				COPY_VALUE(camFovIncrease);
				COPY_VALUE(camFovOffset);
				COPY_VALUE(camFovSpeed);
				COPY_VALUE(camReturnSpeed);
				COPY_VALUE(camReturnLerp);
				COPY_VALUE(camVehicleAnglePitchRate);
				COPY_VALUE(camVehicleAngleYawRate);
				COPY_VALUE(camVehicleAngleRollRate);
				new_asset->camShakeMinSpeed = 0.f;
				new_asset->camShakeMaxSpeed = 0.f;
				new_asset->camShakeMinFreq = 0.f;
				new_asset->camShakeMaxFreq = 0.f;
				new_asset->camShakeMaxAmplitudePitch = 0.f;
				new_asset->camShakeMaxAmplitudeYaw = 0.f;
				new_asset->camShakeMaxAmplitudeRoll = 0.f;
				new_asset->camShakeMaxAmplitudeX = 0.f;
				new_asset->camShakeMaxAmplitudeY = 0.f;
				new_asset->camShakeMaxAmplitudeZ = 0.f;
				new_asset->camShakeMinAmplitudeScale = 0.f;
				new_asset->camShakeTurretInherit = 0;
				COPY_VALUE(vehCam_UseGDT);
				COPY_VALUE(vehCam_anglesPitch);
				COPY_VALUE(vehCam_anglesYaw);
				COPY_VALUE(vehCam_anglesRoll);
				COPY_VALUE(vehCam_offsetX);
				COPY_VALUE(vehCam_offsetY);
				COPY_VALUE(vehCam_offsetZ);
				COPY_VALUE(vehCam_radius);
				COPY_VALUE(vehCam_speedInfluence);
				COPY_VALUE(vehCam_pitchTurnRate);
				COPY_VALUE(vehCam_pitchClamp);
				COPY_VALUE(vehCam_yawTurnRate);
				COPY_VALUE(vehCam_yawClamp);
				COPY_VALUE_CAST(vehCam_zOffsetMode);
				COPY_VALUE(vehCam_anglesPitch3P);
				COPY_VALUE(vehCam_anglesYaw3P);
				COPY_VALUE(vehCam_anglesRoll3P);
				COPY_VALUE(vehCam_offsetX3P);
				COPY_VALUE(vehCam_offsetY3P);
				COPY_VALUE(vehCam_offsetZ3P);
				COPY_VALUE(vehCam_radius3P);
				COPY_VALUE(vehCam_speedInfluence3P);
				COPY_VALUE(vehCam_pitchTurnRate3P);
				COPY_VALUE(vehCam_pitchClamp3P);
				COPY_VALUE(vehCam_yawTurnRate3P);
				new_asset->vehCam_yawTurnRate3PHandbrakeInc = 0.f;
				COPY_VALUE(vehCam_yawClamp3P);
				COPY_VALUE_CAST(vehCam_zOffsetMode3P);
				new_asset->pad4 = 0.f;
				COPY_VALUE(turretWeaponName);
				COPY_VALUE_CAST(turretWeapon);
				COPY_VALUE(turretHorizSpanLeft);
				COPY_VALUE(turretHorizSpanRight);
				COPY_VALUE(turretVertSpanUp);
				COPY_VALUE(turretVertSpanDown);
				COPY_VALUE(turretHorizResistLeft);
				COPY_VALUE(turretHorizResistRight);
				COPY_VALUE(turretVertResistUp);
				COPY_VALUE(turretVertResistDown);
				COPY_VALUE(turretRotRate);
				COPY_VALUE_CAST(turretFireType);
				COPY_VALUE_CAST(turretSpinSnd);
				COPY_VALUE_CAST(turretStopSnd);
				COPY_VALUE(trophyEnabled);
				COPY_VALUE(trophyRadius);
				COPY_VALUE(trophyInactiveRadius);
				COPY_VALUE(trophyAmmoCount);
				COPY_VALUE(trophyReloadTime);
				COPY_ARR(trophyTags);
				COPY_VALUE_CAST(trophyExplodeFx);
				COPY_VALUE_CAST(trophyFlashFx);
				COPY_VALUE_CAST(compassFriendlyIcon);
				COPY_VALUE_CAST(compassEnemyIcon);
				COPY_VALUE_CAST(compassFriendlyAltIcon);
				COPY_VALUE_CAST(compassEnemyAltIcon);
				COPY_VALUE(compassIconWidth);
				COPY_VALUE(compassIconHeight);
				COPY_VALUE_CAST(idleLowSnd);
				COPY_VALUE_CAST(idleHighSnd);
				COPY_VALUE_CAST(engineLowSnd);
				COPY_VALUE_CAST(engineHighSnd);
				new_asset->boostSnd = nullptr;
				COPY_VALUE(engineSndSpeed);
				COPY_VALUE(audioOriginTag);
				COPY_VALUE_CAST(idleLowSndAlt);
				COPY_VALUE_CAST(idleHighSndAlt);
				COPY_VALUE_CAST(engineLowSndAlt);
				COPY_VALUE_CAST(engineHighSndAlt);
				COPY_VALUE(engineSndSpeedAlt);
				COPY_VALUE(audioOriginTagAlt);
				COPY_VALUE_CAST(turretSpinSndAlt);
				COPY_VALUE_CAST(turretStopSndAlt);
				COPY_VALUE_CAST(engineStartUpSnd);
				COPY_VALUE(engineStartUpLength);
				COPY_VALUE_CAST(engineShutdownSnd);
				COPY_VALUE_CAST(engineIdleSnd);
				COPY_VALUE_CAST(engineSustainSnd);
				COPY_VALUE_CAST(engineRampUpSnd);
				COPY_VALUE(engineRampUpLength);
				COPY_VALUE_CAST(engineRampDownSnd);
				COPY_VALUE(engineRampDownLength);
				COPY_VALUE_CAST(suspensionSoftSnd);
				COPY_VALUE(suspensionSoftCompression);
				COPY_VALUE_CAST(suspensionHardSnd);
				COPY_VALUE(suspensionHardCompression);
				COPY_VALUE_CAST(collisionSnd);
				COPY_VALUE(collisionBlendSpeed);
				COPY_VALUE_CAST(speedSnd);
				COPY_VALUE(speedSndBlendSpeed);

				for (auto i = 0; i < 31; i++)
				{
					new_asset->surfaceSnds[i] = reinterpret_cast<zonetool::h1::snd_alias_list_t*>(asset->surfaceSnds[i]);
				}

				COPY_VALUE(surfaceSndBlendSpeed);
				COPY_VALUE(slideVolume);
				COPY_VALUE(slideBlendSpeed);
				COPY_VALUE(inAirPitch);
				COPY_VALUE(soundTriggerOverrideZone);
				COPY_VALUE(soundTriggerOverrideReverb);
				COPY_VALUE(soundTriggerOverrideMix);
				COPY_VALUE(soundTriggerOverrideFilter);
				COPY_VALUE(soundTriggerOverrideOcclusion);
				COPY_VALUE(soundTriggerOverrideAmbient);
				COPY_VALUE(soundTriggerOverrideAmbientEvents);

				return new_asset;
			}

			void dump(VehicleDef* asset)
			{
				utils::memory::allocator allocator;
				auto* converted_asset = convert(asset, allocator);
				zonetool::h1::vehicle_def::dump(converted_asset);
			}
		}
	}
}