#include <std_include.hpp>

#include "definitions.hpp"

namespace shader::asm_
{
	std::unordered_map<std::uint32_t, const char*> opcode_names =
	{
		{D3D10_SB_OPCODE_ADD, "add"},
		{D3D10_SB_OPCODE_AND, "and"},
		{D3D10_SB_OPCODE_BREAK, "break"},
		{D3D10_SB_OPCODE_BREAKC, "breakc"},
		{D3D10_SB_OPCODE_CALL, "call"},
		{D3D10_SB_OPCODE_CALLC, "callc"},
		{D3D10_SB_OPCODE_CASE, "case"},
		{D3D10_SB_OPCODE_CONTINUE, "continue"},
		{D3D10_SB_OPCODE_CONTINUEC, "continuec"},
		{D3D10_SB_OPCODE_CUT, "cut"},
		{D3D10_SB_OPCODE_DEFAULT, "default"},
		{D3D10_SB_OPCODE_DERIV_RTX, "deriv_rtx"},
		{D3D10_SB_OPCODE_DERIV_RTY, "deriv_rty"},
		{D3D10_SB_OPCODE_DISCARD, "discard"},
		{D3D10_SB_OPCODE_DIV, "div"},
		{D3D10_SB_OPCODE_DP2, "dp2"},
		{D3D10_SB_OPCODE_DP3, "dp3"},
		{D3D10_SB_OPCODE_DP4, "dp4"},
		{D3D10_SB_OPCODE_ELSE, "else"},
		{D3D10_SB_OPCODE_EMIT, "emit"},
		{D3D10_SB_OPCODE_EMITTHENCUT, "emitthencut"},
		{D3D10_SB_OPCODE_ENDIF, "endif"},
		{D3D10_SB_OPCODE_ENDLOOP, "endloop"},
		{D3D10_SB_OPCODE_ENDSWITCH, "endswitch"},
		{D3D10_SB_OPCODE_EQ, "eq"},
		{D3D10_SB_OPCODE_EXP, "exp"},
		{D3D10_SB_OPCODE_FRC, "frc"},
		{D3D10_SB_OPCODE_FTOI, "ftoi"},
		{D3D10_SB_OPCODE_FTOU, "ftou"},
		{D3D10_SB_OPCODE_GE, "ge"},
		{D3D10_SB_OPCODE_IADD, "iadd"},
		{D3D10_SB_OPCODE_IF, "if"},
		{D3D10_SB_OPCODE_IEQ, "ieq"},
		{D3D10_SB_OPCODE_IGE, "ige"},
		{D3D10_SB_OPCODE_ILT, "ilt"},
		{D3D10_SB_OPCODE_IMAD, "imad"},
		{D3D10_SB_OPCODE_IMAX, "imax"},
		{D3D10_SB_OPCODE_IMIN, "imin"},
		{D3D10_SB_OPCODE_IMUL, "imul"},
		{D3D10_SB_OPCODE_INE, "ine"},
		{D3D10_SB_OPCODE_INEG, "ineg"},
		{D3D10_SB_OPCODE_ISHL, "ishl"},
		{D3D10_SB_OPCODE_ISHR, "ishr"},
		{D3D10_SB_OPCODE_ITOF, "itof"},
		{D3D10_SB_OPCODE_LABEL, "label"},
		{D3D10_SB_OPCODE_LD, "ld"},
		{D3D10_SB_OPCODE_LD_MS, "ld_ms"},
		{D3D10_SB_OPCODE_LOG, "log"},
		{D3D10_SB_OPCODE_LOOP, "loop"},
		{D3D10_SB_OPCODE_LT, "lt"},
		{D3D10_SB_OPCODE_MAD, "mad"},
		{D3D10_SB_OPCODE_MIN, "min"},
		{D3D10_SB_OPCODE_MAX, "max"},
		{D3D10_SB_OPCODE_CUSTOMDATA, "customdata"},
		{D3D10_SB_OPCODE_MOV, "mov"},
		{D3D10_SB_OPCODE_MOVC, "movc"},
		{D3D10_SB_OPCODE_MUL, "mul"},
		{D3D10_SB_OPCODE_NE, "ne"},
		{D3D10_SB_OPCODE_NOP, "nop"},
		{D3D10_SB_OPCODE_NOT, "not"},
		{D3D10_SB_OPCODE_OR, "or"},
		{D3D10_SB_OPCODE_RESINFO, "resinfo"},
		{D3D10_SB_OPCODE_RET, "ret"},
		{D3D10_SB_OPCODE_RETC, "retc"},
		{D3D10_SB_OPCODE_ROUND_NE, "round_ne"},
		{D3D10_SB_OPCODE_ROUND_NI, "round_ni"},
		{D3D10_SB_OPCODE_ROUND_PI, "round_pi"},
		{D3D10_SB_OPCODE_ROUND_Z, "round_z"},
		{D3D10_SB_OPCODE_RSQ, "rsq"},
		{D3D10_SB_OPCODE_SAMPLE, "sample"},
		{D3D10_SB_OPCODE_SAMPLE_C, "sample_c"},
		{D3D10_SB_OPCODE_SAMPLE_C_LZ, "sample_c_lz"},
		{D3D10_SB_OPCODE_SAMPLE_L, "sample_l"},
		{D3D10_SB_OPCODE_SAMPLE_D, "sample_d"},
		{D3D10_SB_OPCODE_SAMPLE_B, "sample_b"},
		{D3D10_SB_OPCODE_SQRT, "sqrt"},
		{D3D10_SB_OPCODE_SWITCH, "switch"},
		{D3D10_SB_OPCODE_SINCOS, "sincos"},
		{D3D10_SB_OPCODE_UDIV, "udiv"},
		{D3D10_SB_OPCODE_ULT, "ult"},
		{D3D10_SB_OPCODE_UGE, "uge"},
		{D3D10_SB_OPCODE_UMUL, "umul"},
		{D3D10_SB_OPCODE_UMAD, "umad"},
		{D3D10_SB_OPCODE_UMAX, "umax"},
		{D3D10_SB_OPCODE_UMIN, "umin"},
		{D3D10_SB_OPCODE_USHR, "ushr"},
		{D3D10_SB_OPCODE_UTOF, "utof"},
		{D3D10_SB_OPCODE_XOR, "xor"},
		{D3D10_SB_OPCODE_DCL_RESOURCE, "dcl_resource"},
		{D3D10_SB_OPCODE_DCL_CONSTANT_BUFFER, "dcl_constantBuffer"},
		{D3D10_SB_OPCODE_DCL_SAMPLER, "dcl_sampler"},
		{D3D10_SB_OPCODE_DCL_INDEX_RANGE, "dcl_indexRange"},
		{D3D10_SB_OPCODE_DCL_GS_OUTPUT_PRIMITIVE_TOPOLOGY, "dcl_outputTopology"},
		{D3D10_SB_OPCODE_DCL_GS_INPUT_PRIMITIVE, "dcl_inputPrimitive"},
		{D3D10_SB_OPCODE_DCL_MAX_OUTPUT_VERTEX_COUNT, "dcl_maxOutputVertexCount"},
		{D3D10_SB_OPCODE_DCL_INPUT, "dcl_input"},
		{D3D10_SB_OPCODE_DCL_INPUT_SGV, "dcl_input_sgv"},
		{D3D10_SB_OPCODE_DCL_INPUT_SIV, "dcl_input_siv"},
		{D3D10_SB_OPCODE_DCL_INPUT_PS, "dcl_input_ps"},
		{D3D10_SB_OPCODE_DCL_INPUT_PS_SGV, "dcl_input_ps_sgv"},
		{D3D10_SB_OPCODE_DCL_INPUT_PS_SIV, "dcl_input_ps_siv"},
		{D3D10_SB_OPCODE_DCL_OUTPUT, "dcl_output"},
		{D3D10_SB_OPCODE_DCL_OUTPUT_SGV, "dcl_output_sgv"},
		{D3D10_SB_OPCODE_DCL_OUTPUT_SIV, "dcl_output_siv"},
		{D3D10_SB_OPCODE_DCL_TEMPS, "dcl_temps"},
		{D3D10_SB_OPCODE_DCL_INDEXABLE_TEMP, "dcl_indexableTemp"},
		{D3D10_SB_OPCODE_DCL_GLOBAL_FLAGS, "dcl_globalFlags"},
		{D3D10_SB_OPCODE_RESERVED0, "reserved0"},
		{D3D10_1_SB_OPCODE_LOD, "lod"},
		{D3D10_1_SB_OPCODE_GATHER4, "gather4"},
		{D3D10_1_SB_OPCODE_SAMPLE_POS, "sample_pos"},
		{D3D10_1_SB_OPCODE_SAMPLE_INFO, "sample_info"},
		{D3D10_1_SB_OPCODE_RESERVED1, "reserved1"},
		{D3D11_SB_OPCODE_HS_DECLS, "hs_decls"},
		{D3D11_SB_OPCODE_HS_CONTROL_POINT_PHASE, "hs_control_point_phase"},
		{D3D11_SB_OPCODE_HS_FORK_PHASE, "hs_fork_phase"},
		{D3D11_SB_OPCODE_HS_JOIN_PHASE, "hs_join_phase"},
		{D3D11_SB_OPCODE_EMIT_STREAM, "emit_stream"},
		{D3D11_SB_OPCODE_CUT_STREAM, "cut_stream"},
		{D3D11_SB_OPCODE_EMITTHENCUT_STREAM, "emitthencut_stream"},
		{D3D11_SB_OPCODE_INTERFACE_CALL, "interface_call"},
		{D3D11_SB_OPCODE_BUFINFO, "bufinfo"},
		{D3D11_SB_OPCODE_DERIV_RTX_COARSE, "deriv_rtx_coarse"},
		{D3D11_SB_OPCODE_DERIV_RTX_FINE, "deriv_rtx_fine"},
		{D3D11_SB_OPCODE_DERIV_RTY_COARSE, "deriv_rty_coarse"},
		{D3D11_SB_OPCODE_DERIV_RTY_FINE, "deriv_rty_fine"},
		{D3D11_SB_OPCODE_GATHER4_C, "gather4_c"},
		{D3D11_SB_OPCODE_GATHER4_PO, "gather4_po"},
		{D3D11_SB_OPCODE_GATHER4_PO_C, "gather4_po_c"},
		{D3D11_SB_OPCODE_RCP, "rcp"},
		{D3D11_SB_OPCODE_F32TOF16, "f32tof16"},
		{D3D11_SB_OPCODE_F16TOF32, "f16tof32"},
		{D3D11_SB_OPCODE_UADDC, "uaddc"},
		{D3D11_SB_OPCODE_USUBB, "usubb"},
		{D3D11_SB_OPCODE_COUNTBITS, "countbits"},
		{D3D11_SB_OPCODE_FIRSTBIT_HI, "firstbit_hi"},
		{D3D11_SB_OPCODE_FIRSTBIT_LO, "firstbit_lo"},
		{D3D11_SB_OPCODE_FIRSTBIT_SHI, "firstbit_shi"},
		{D3D11_SB_OPCODE_UBFE, "ubfe"},
		{D3D11_SB_OPCODE_IBFE, "ibfe"},
		{D3D11_SB_OPCODE_BFI, "bfi"},
		{D3D11_SB_OPCODE_BFREV, "bfrev"},
		{D3D11_SB_OPCODE_SWAPC, "swapc"},
		{D3D11_SB_OPCODE_DCL_STREAM, "dcl_stream"},
		{D3D11_SB_OPCODE_DCL_FUNCTION_BODY, "dcl_function_body"},
		{D3D11_SB_OPCODE_DCL_FUNCTION_TABLE, "dcl_function_table"},
		{D3D11_SB_OPCODE_DCL_INTERFACE, "dcl_interface"},
		{D3D11_SB_OPCODE_DCL_INPUT_CONTROL_POINT_COUNT, "dcl_input_control_point_count"},
		{D3D11_SB_OPCODE_DCL_OUTPUT_CONTROL_POINT_COUNT, "dcl_output_control_point_count"},
		{D3D11_SB_OPCODE_DCL_TESS_DOMAIN, "dcl_tess_domain"},
		{D3D11_SB_OPCODE_DCL_TESS_PARTITIONING, "dcl_tess_partitioning"},
		{D3D11_SB_OPCODE_DCL_TESS_OUTPUT_PRIMITIVE, "dcl_tess_output_primitive"},
		{D3D11_SB_OPCODE_DCL_HS_MAX_TESSFACTOR, "dcl_hs_max_tessfactor"},
		{D3D11_SB_OPCODE_DCL_HS_FORK_PHASE_INSTANCE_COUNT, "dcl_hs_fork_phase_instance_count"},
		{D3D11_SB_OPCODE_DCL_HS_JOIN_PHASE_INSTANCE_COUNT, "dcl_hs_join_phase_instance_count"},
		{D3D11_SB_OPCODE_DCL_THREAD_GROUP, "dcl_thread_group"},
		{D3D11_SB_OPCODE_DCL_UNORDERED_ACCESS_VIEW_TYPED, "dcl_unordered_access_view_typed"},
		{D3D11_SB_OPCODE_DCL_UNORDERED_ACCESS_VIEW_RAW, "dcl_unordered_access_view_raw"},
		{D3D11_SB_OPCODE_DCL_UNORDERED_ACCESS_VIEW_STRUCTURED, "dcl_unordered_access_view_structured"},
		{D3D11_SB_OPCODE_DCL_THREAD_GROUP_SHARED_MEMORY_RAW, "dcl_thread_group_shared_memory_raw"},
		{D3D11_SB_OPCODE_DCL_THREAD_GROUP_SHARED_MEMORY_STRUCTURED, "dcl_thread_group_shared_memory_structured"},
		{D3D11_SB_OPCODE_DCL_RESOURCE_RAW, "dcl_resource_raw"},
		{D3D11_SB_OPCODE_DCL_RESOURCE_STRUCTURED, "dcl_resource_structured"},
		{D3D11_SB_OPCODE_LD_UAV_TYPED, "ld_uav_typed"},
		{D3D11_SB_OPCODE_STORE_UAV_TYPED, "store_uav_typed"},
		{D3D11_SB_OPCODE_LD_RAW, "ld_raw"},
		{D3D11_SB_OPCODE_STORE_RAW, "store_raw"},
		{D3D11_SB_OPCODE_LD_STRUCTURED, "ld_structured"},
		{D3D11_SB_OPCODE_STORE_STRUCTURED, "store_structured"},
		{D3D11_SB_OPCODE_ATOMIC_AND, "atomic_and"},
		{D3D11_SB_OPCODE_ATOMIC_OR, "atomic_or"},
		{D3D11_SB_OPCODE_ATOMIC_XOR, "atomic_xor"},
		{D3D11_SB_OPCODE_ATOMIC_CMP_STORE, "atomic_cmp_store"},
		{D3D11_SB_OPCODE_ATOMIC_IADD, "atomic_iadd"},
		{D3D11_SB_OPCODE_ATOMIC_IMAX, "atomic_imax"},
		{D3D11_SB_OPCODE_ATOMIC_IMIN, "atomic_imin"},
		{D3D11_SB_OPCODE_ATOMIC_UMAX, "atomic_umax"},
		{D3D11_SB_OPCODE_ATOMIC_UMIN, "atomic_umin"},
		{D3D11_SB_OPCODE_IMM_ATOMIC_ALLOC, "imm_atomic_alloc"},
		{D3D11_SB_OPCODE_IMM_ATOMIC_CONSUME, "imm_atomic_consume"},
		{D3D11_SB_OPCODE_IMM_ATOMIC_IADD, "imm_atomic_iadd"},
		{D3D11_SB_OPCODE_IMM_ATOMIC_AND, "imm_atomic_and"},
		{D3D11_SB_OPCODE_IMM_ATOMIC_OR, "imm_atomic_or"},
		{D3D11_SB_OPCODE_IMM_ATOMIC_XOR, "imm_atomic_xor"},
		{D3D11_SB_OPCODE_IMM_ATOMIC_EXCH, "imm_atomic_exch"},
		{D3D11_SB_OPCODE_IMM_ATOMIC_CMP_EXCH, "imm_atomic_cmp_exch"},
		{D3D11_SB_OPCODE_IMM_ATOMIC_IMAX, "imm_atomic_imax"},
		{D3D11_SB_OPCODE_IMM_ATOMIC_IMIN, "imm_atomic_imin"},
		{D3D11_SB_OPCODE_IMM_ATOMIC_UMAX, "imm_atomic_umax"},
		{D3D11_SB_OPCODE_IMM_ATOMIC_UMIN, "imm_atomic_umin"},
		{D3D11_SB_OPCODE_SYNC, "sync"},
		{D3D11_SB_OPCODE_DADD, "dadd"},
		{D3D11_SB_OPCODE_DMAX, "dmax"},
		{D3D11_SB_OPCODE_DMIN, "dmin"},
		{D3D11_SB_OPCODE_DMUL, "dmul"},
		{D3D11_SB_OPCODE_DEQ, "deq"},
		{D3D11_SB_OPCODE_DGE, "dge"},
		{D3D11_SB_OPCODE_DLT, "dlt"},
		{D3D11_SB_OPCODE_DNE, "dne"},
		{D3D11_SB_OPCODE_DMOV, "dmov"},
		{D3D11_SB_OPCODE_DMOVC, "dmovc"},
		{D3D11_SB_OPCODE_DTOF, "dtof"},
		{D3D11_SB_OPCODE_FTOD, "ftod"},
		{D3D11_SB_OPCODE_EVAL_SNAPPED, "eval_snapped"},
		{D3D11_SB_OPCODE_EVAL_SAMPLE_INDEX, "eval_sample_index"},
		{D3D11_SB_OPCODE_EVAL_CENTROID, "eval_centroid"},
		{D3D11_SB_OPCODE_DCL_GS_INSTANCE_COUNT, "dcl_gs_instance_count"},
		{D3D11_SB_OPCODE_ABORT, "abort"},
		{D3D11_SB_OPCODE_DEBUG_BREAK, "debug_break"},
		{D3D11_SB_OPCODE_RESERVED0, "reserved0"},
		{D3D11_1_SB_OPCODE_DDIV, "ddiv"},
		{D3D11_1_SB_OPCODE_DFMA, "dfma"},
		{D3D11_1_SB_OPCODE_DRCP, "drcp"},
		{D3D11_1_SB_OPCODE_MSAD, "msad"},
		{D3D11_1_SB_OPCODE_DTOI, "dtoi"},
		{D3D11_1_SB_OPCODE_DTOU, "dtou"},
		{D3D11_1_SB_OPCODE_ITOD, "itod"},
		{D3D11_1_SB_OPCODE_UTOD, "utod"},
		{D3D11_1_SB_OPCODE_RESERVED0, "reserved0"},
		{D3DWDDM1_3_SB_OPCODE_GATHER4_FEEDBACK, "gather4_feedback"},
		{D3DWDDM1_3_SB_OPCODE_GATHER4_C_FEEDBACK, "gather4_c_feedback"},
		{D3DWDDM1_3_SB_OPCODE_GATHER4_PO_FEEDBACK, "gather4_po_feedback"},
		{D3DWDDM1_3_SB_OPCODE_GATHER4_PO_C_FEEDBACK, "gather4_po_c_feedback"},
		{D3DWDDM1_3_SB_OPCODE_LD_FEEDBACK, "ld_feedback"},
		{D3DWDDM1_3_SB_OPCODE_LD_MS_FEEDBACK, "ld_ms_feedback"},
		{D3DWDDM1_3_SB_OPCODE_LD_UAV_TYPED_FEEDBACK, "ld_uav_typed_feedback"},
		{D3DWDDM1_3_SB_OPCODE_LD_RAW_FEEDBACK, "ld_raw_feedback"},
		{D3DWDDM1_3_SB_OPCODE_LD_STRUCTURED_FEEDBACK, "ld_structured_feedback"},
		{D3DWDDM1_3_SB_OPCODE_SAMPLE_L_FEEDBACK, "sample_l_feedback"},
		{D3DWDDM1_3_SB_OPCODE_SAMPLE_C_LZ_FEEDBACK, "sample_c_lz_feedback"},
		{D3DWDDM1_3_SB_OPCODE_SAMPLE_CLAMP_FEEDBACK, "sample_clamp_feedback"},
		{D3DWDDM1_3_SB_OPCODE_SAMPLE_B_CLAMP_FEEDBACK, "sample_b_clamp_feedback"},
		{D3DWDDM1_3_SB_OPCODE_SAMPLE_D_CLAMP_FEEDBACK, "sample_d_clamp_feedback"},
		{D3DWDDM1_3_SB_OPCODE_SAMPLE_C_CLAMP_FEEDBACK, "sample_c_clamp_feedback"},
		{D3DWDDM1_3_SB_OPCODE_CHECK_ACCESS_FULLY_MAPPED, "check_access_fully_mapped"},
		{D3DWDDM1_3_SB_OPCODE_RESERVED0, "reserved0"},
	};

	const char* get_resource_dimension_name(const std::uint32_t dimension)
	{
		switch (dimension)
		{
		case D3D10_SB_RESOURCE_DIMENSION_BUFFER:
			return "buffer";
		case D3D10_SB_RESOURCE_DIMENSION_TEXTURE1D:
			return "texture1d";
		case D3D10_SB_RESOURCE_DIMENSION_TEXTURE2D:
			return "texture2d";
		case D3D10_SB_RESOURCE_DIMENSION_TEXTURE2DMS:
			return "texture2dMs";
		case D3D10_SB_RESOURCE_DIMENSION_TEXTURE3D:
			return "texture3d";
		case D3D10_SB_RESOURCE_DIMENSION_TEXTURECUBE:
			return "texturecube";
		case D3D10_SB_RESOURCE_DIMENSION_TEXTURE1DARRAY:
			return "texture1dArray";
		case D3D10_SB_RESOURCE_DIMENSION_TEXTURE2DARRAY:
			return "texture2dArray";
		case D3D10_SB_RESOURCE_DIMENSION_TEXTURE2DMSARRAY:
			return "texture2dMsArray";
		case D3D10_SB_RESOURCE_DIMENSION_TEXTURECUBEARRAY:
			return "textureCubeArray";
		case D3D11_SB_RESOURCE_DIMENSION_RAW_BUFFER:
			return "rawBuffer";
		case D3D11_SB_RESOURCE_DIMENSION_STRUCTURED_BUFFER:
			return "sturcturedBuffer";
		}

		return "unknown";
	}

	const char* get_return_type_name(const std::uint32_t type)
	{
		switch (type)
		{
		case D3D10_SB_RETURN_TYPE_UNORM:
			return "unorm";
		case D3D10_SB_RETURN_TYPE_SNORM:
			return "snorm";
		case D3D10_SB_RETURN_TYPE_SINT:
			return "sint";
		case D3D10_SB_RETURN_TYPE_UINT:
			return "uint";
		case D3D10_SB_RETURN_TYPE_FLOAT:
			return "float";
		case D3D10_SB_RETURN_TYPE_MIXED:
			return "mixed";
		case D3D11_SB_RETURN_TYPE_DOUBLE:
			return "double";
		case D3D11_SB_RETURN_TYPE_CONTINUED:
			return "continued";
		}

		return "unknown";
	}

	const char* get_name_token(const std::uint32_t type)
	{
		switch (type)
		{
		case D3D10_SB_NAME_POSITION:
			return "position";
		case D3D10_SB_NAME_CLIP_DISTANCE:
			return "clipDistance";
		case D3D10_SB_NAME_CULL_DISTANCE:
			return "cullDistance";
		case D3D10_SB_NAME_RENDER_TARGET_ARRAY_INDEX:
			return "renderTargetArrayIndex";
		case D3D10_SB_NAME_VIEWPORT_ARRAY_INDEX:
			return "viewportArrayIndex";
		case D3D10_SB_NAME_VERTEX_ID:
			return "vertexId";
		case D3D10_SB_NAME_PRIMITIVE_ID:
			return "primitive id";
		case D3D10_SB_NAME_INSTANCE_ID:
			return "instanceId";
		case D3D10_SB_NAME_IS_FRONT_FACE:
			return "isFrontFace";
		case D3D10_SB_NAME_SAMPLE_INDEX:
			return "sampleIndex";
		case D3D11_SB_NAME_FINAL_QUAD_U_EQ_0_EDGE_TESSFACTOR:
			return "finalQuadUEq0EdgeTessFactor";
		case D3D11_SB_NAME_FINAL_QUAD_V_EQ_0_EDGE_TESSFACTOR:
			return "finalQuadVEq0EdgeTessFactor";
		case D3D11_SB_NAME_FINAL_QUAD_U_EQ_1_EDGE_TESSFACTOR:
			return "finalQuadUEq1EdgeTessFactor";
		case D3D11_SB_NAME_FINAL_QUAD_V_EQ_1_EDGE_TESSFACTOR:
			return "finalQuadVEq1EdgeTessFactor";
		case D3D11_SB_NAME_FINAL_QUAD_U_INSIDE_TESSFACTOR:
			return "finalQuadUInsideTessFactor";
		case D3D11_SB_NAME_FINAL_QUAD_V_INSIDE_TESSFACTOR:
			return "finalQuadVInsideTessFactor";
		case D3D11_SB_NAME_FINAL_TRI_U_EQ_0_EDGE_TESSFACTOR:
			return "finalTriUEq0EdgeTessFactor";
		case D3D11_SB_NAME_FINAL_TRI_V_EQ_0_EDGE_TESSFACTOR:
			return "finalTriVEq0EdgeTessFactor";
		case D3D11_SB_NAME_FINAL_TRI_W_EQ_0_EDGE_TESSFACTOR:
			return "finalTriWEq0EdgeTessFactor";
		case D3D11_SB_NAME_FINAL_TRI_INSIDE_TESSFACTOR:
			return "finalTriInsideTessFactor";
		case D3D11_SB_NAME_FINAL_LINE_DETAIL_TESSFACTOR:
			return "finalLineDetailTessFactor";
		case D3D11_SB_NAME_FINAL_LINE_DENSITY_TESSFACTOR:
			return "finalLineDensityTessFactor";
		}

		return "undefined";
	}
}
