#pragma once

#include "include.hpp"

#include "assets/clipmap.hpp"
#include "assets/comworld.hpp"
#include "assets/fxeffectdef.hpp"
#include "assets/fxworld.hpp"
#include "assets/gfximage.hpp"
#include "assets/gfxworld.hpp"
#include "assets/mapents.hpp"
#include "assets/material.hpp"
#include "assets/scriptabledef.hpp"
#include "assets/sound.hpp"
#include "assets/xanim.hpp"
#include "assets/xmodel.hpp"
#include "assets/xsurface.hpp"

#include "assets/computeshader.hpp"
#include "assets/domainshader.hpp"
#include "assets/hullshader.hpp"
#include "assets/pixelshader.hpp"
#include "assets/vertexdecl.hpp"
#include "assets/vertexshader.hpp"
#include "assets/techset.hpp"