#include <std_include.hpp>

#include "zonetool/h1/converter/iw7/include.hpp"
#include "techset.hpp"
#ifdef EXPERIMENTAL_IW7

#include "zonetool/iw7/assets/techset.hpp"
#include "zonetool/iw7/assets/computeshader.hpp"
#include "zonetool/iw7/assets/vertexshader.hpp"
#include "zonetool/iw7/assets/vertexdecl.hpp"
#include "zonetool/iw7/assets/hullshader.hpp"
#include "zonetool/iw7/assets/domainshader.hpp"
#include "zonetool/iw7/assets/pixelshader.hpp"

#include <utils/io.hpp>
namespace zonetool::h1
{
	namespace converter::iw7
	{
		namespace techset
		{
			std::unordered_map<unsigned short, unsigned short> mapped_code_consts =
			{
				{zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION, zonetool::iw7::CONST_SRC_CODE_LIGHT_POSITION},
				{zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE, zonetool::iw7::CONST_SRC_CODE_LIGHT_DIFFUSE},
				{zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE, zonetool::iw7::CONST_SRC_CODE_LIGHT_PHYSICALSIZE},
				{zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET, zonetool::iw7::CONST_SRC_CODE_LIGHT_FADEOFFSET},
				{zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPECULAR},
				{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTDIR},
				{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTFACTORS},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT, zonetool::iw7::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM, zonetool::iw7::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION1, zonetool::iw7::CONST_SRC_CODE_LIGHT_POSITION1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE1, zonetool::iw7::CONST_SRC_CODE_LIGHT_DIFFUSE1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE1, zonetool::iw7::CONST_SRC_CODE_LIGHT_PHYSICALSIZE1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET1, zonetool::iw7::CONST_SRC_CODE_LIGHT_FADEOFFSET1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR1, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPECULAR1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR1, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTDIR1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS1, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTFACTORS1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT1, zonetool::iw7::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM1, zonetool::iw7::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION2, zonetool::iw7::CONST_SRC_CODE_LIGHT_POSITION2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE2, zonetool::iw7::CONST_SRC_CODE_LIGHT_DIFFUSE2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE2, zonetool::iw7::CONST_SRC_CODE_LIGHT_PHYSICALSIZE2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET2, zonetool::iw7::CONST_SRC_CODE_LIGHT_FADEOFFSET2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR2, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPECULAR2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR2, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTDIR2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS2, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTFACTORS2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT2, zonetool::iw7::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM2, zonetool::iw7::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION3, zonetool::iw7::CONST_SRC_CODE_LIGHT_POSITION3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE3, zonetool::iw7::CONST_SRC_CODE_LIGHT_DIFFUSE3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE3, zonetool::iw7::CONST_SRC_CODE_LIGHT_PHYSICALSIZE3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET3, zonetool::iw7::CONST_SRC_CODE_LIGHT_FADEOFFSET3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR3, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPECULAR3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR3, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTDIR3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS3, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTFACTORS3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT3, zonetool::iw7::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM3, zonetool::iw7::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_2, zonetool::iw7::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_3, zonetool::iw7::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_2, zonetool::iw7::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_3, zonetool::iw7::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_2, zonetool::iw7::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_3, zonetool::iw7::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_2, zonetool::iw7::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_3, zonetool::iw7::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_2, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_3, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_2, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_3, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_2, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_3, zonetool::iw7::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_2, zonetool::iw7::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_3, zonetool::iw7::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_2, zonetool::iw7::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_2},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_3, zonetool::iw7::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_3},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_DYN_COUNT, zonetool::iw7::CONST_SRC_CODE_LIGHT_DYN_COUNT},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_DYN_TYPES, zonetool::iw7::CONST_SRC_CODE_LIGHT_DYN_TYPES},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_DYN_SHADOW_TYPES, zonetool::iw7::CONST_SRC_CODE_LIGHT_DYN_SHADOW_TYPES},
				{zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_COLOR, zonetool::iw7::CONST_SRC_CODE_PARTICLE_CLOUD_COLOR},
				{zonetool::h1::CONST_SRC_CODE_GAMETIME, zonetool::iw7::CONST_SRC_CODE_GAMETIME},
				//{zonetool::h1::CONST_SRC_CODE_SYSTEMTIME, zonetool::iw7::CONST_SRC_CODE_SYSTEMTIME},
				//{zonetool::h1::CONST_SRC_CODE_GENERIC_MATERIAL_DATA, zonetool::iw7::CONST_SRC_CODE_GENERIC_MATERIAL_DATA},
				{zonetool::h1::CONST_SRC_CODE_EYEOFFSET, zonetool::iw7::CONST_SRC_CODE_EYEOFFSET},
				{zonetool::h1::CONST_SRC_CODE_WORLD_MATRIX_EYE_OFFSET, zonetool::iw7::CONST_SRC_CODE_WORLD_MATRIX_EYE_OFFSET},
				{zonetool::h1::CONST_SRC_CODE_EMBLEM_LUT_SELECTOR, zonetool::iw7::CONST_SRC_CODE_HUD_OUTLINE_PARMS},
				//{zonetool::h1::CONST_SRC_CODE_MODEL_VELOCITY_PARMS, zonetool::iw7::CONST_SRC_CODE_MODEL_VELOCITY_PARMS},
				//{zonetool::h1::CONST_SRC_CODE_MODEL_VELOCITY_SKINNED_PARMS, zonetool::iw7::CONST_SRC_CODE_MODEL_VELOCITY_SKINNED_PARMS},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL0, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROL0},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL1, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROL1},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL2, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROL2},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL3, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROL3},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL4, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROL4},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL5, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROL5},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL6, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROL6},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL7, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROL7},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL8, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROL8},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL9, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROL9},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROLA, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROLA},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROLB, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROLB},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROLC, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROLC},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROLD, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROLD},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROLE, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROLE},
				{zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROLF, zonetool::iw7::CONST_SRC_CODE_POSTFX_CONTROLF},
				//{zonetool::h1::CONST_SRC_CODE_SCRIPT_PARMS, zonetool::iw7::CONST_SRC_CODE_SCRIPT_PARMS},
				//{zonetool::h1::CONST_SRC_CODE_EFFECT_MODEL_COLOR, zonetool::iw7::CONST_SRC_CODE_EFFECT_MODEL_COLOR},
				//{zonetool::h1::CONST_SRC_CODE_EFFECT_MODEL_COLOR_EMISSIVE, zonetool::iw7::CONST_SRC_CODE_EFFECT_MODEL_COLOR_EMISSIVE},
				{zonetool::h1::CONST_SRC_CODE_FILTER_TAP_0, zonetool::iw7::CONST_SRC_CODE_FILTER_TAP_0},
				{zonetool::h1::CONST_SRC_CODE_FILTER_TAP_1, zonetool::iw7::CONST_SRC_CODE_FILTER_TAP_1},
				{zonetool::h1::CONST_SRC_CODE_FILTER_TAP_2, zonetool::iw7::CONST_SRC_CODE_FILTER_TAP_2},
				{zonetool::h1::CONST_SRC_CODE_FILTER_TAP_3, zonetool::iw7::CONST_SRC_CODE_FILTER_TAP_3},
				{zonetool::h1::CONST_SRC_CODE_FILTER_TAP_4, zonetool::iw7::CONST_SRC_CODE_FILTER_TAP_4},
				{zonetool::h1::CONST_SRC_CODE_FILTER_TAP_5, zonetool::iw7::CONST_SRC_CODE_FILTER_TAP_5},
				{zonetool::h1::CONST_SRC_CODE_FILTER_TAP_6, zonetool::iw7::CONST_SRC_CODE_FILTER_TAP_6},
				{zonetool::h1::CONST_SRC_CODE_FILTER_TAP_7, zonetool::iw7::CONST_SRC_CODE_FILTER_TAP_7},
				{zonetool::h1::CONST_SRC_CODE_FILTER_TAP_8, zonetool::iw7::CONST_SRC_CODE_FILTER_TAP_8},
				{zonetool::h1::CONST_SRC_CODE_FILTER_TAP_9, zonetool::iw7::CONST_SRC_CODE_FILTER_TAP_9},
				{zonetool::h1::CONST_SRC_CODE_FILTER_TAP_10, zonetool::iw7::CONST_SRC_CODE_FILTER_TAP_10},
				{zonetool::h1::CONST_SRC_CODE_FILTER_TAP_11, zonetool::iw7::CONST_SRC_CODE_FILTER_TAP_11},
				{zonetool::h1::CONST_SRC_CODE_COLOR_MATRIX_R, zonetool::iw7::CONST_SRC_CODE_COLOR_MATRIX_R},
				{zonetool::h1::CONST_SRC_CODE_COLOR_MATRIX_G, zonetool::iw7::CONST_SRC_CODE_COLOR_MATRIX_G},
				{zonetool::h1::CONST_SRC_CODE_COLOR_MATRIX_B, zonetool::iw7::CONST_SRC_CODE_COLOR_MATRIX_B},
				{zonetool::h1::CONST_SRC_CODE_RENDER_TARGET_SIZE, zonetool::iw7::CONST_SRC_CODE_RENDER_TARGET_SIZE},
				{zonetool::h1::CONST_SRC_CODE_RENDER_SOURCE_SIZE, zonetool::iw7::CONST_SRC_CODE_RENDER_SOURCE_SIZE},
				{zonetool::h1::CONST_SRC_CODE_VEIL_PARAMS, zonetool::iw7::CONST_SRC_CODE_VEIL_PARAMS},
				{zonetool::h1::CONST_SRC_CODE_FXAA_RCPFRAMEOPT, zonetool::iw7::CONST_SRC_CODE_FXAA_RCPFRAMEOPT},
				{zonetool::h1::CONST_SRC_CODE_VOLUME_LIGHT_SCATTER_1, zonetool::iw7::CONST_SRC_CODE_VOLUME_LIGHT_SCATTER_1},
				{zonetool::h1::CONST_SRC_CODE_VOLUME_LIGHT_SCATTER_2, zonetool::iw7::CONST_SRC_CODE_VOLUME_LIGHT_SCATTER_2},
				{zonetool::h1::CONST_SRC_CODE_VOLUME_LIGHT_SCATTER_3, zonetool::iw7::CONST_SRC_CODE_VOLUME_LIGHT_SCATTER_3},
				{zonetool::h1::CONST_SRC_CODE_MODEL_LIGHTMAP_PARAMS, zonetool::iw7::CONST_SRC_CODE_MODEL_LIGHTMAP_PARAMS},
				{zonetool::h1::CONST_SRC_CODE_NEARPLANE_ORG, zonetool::iw7::CONST_SRC_CODE_NEARPLANE_ORG},
				{zonetool::h1::CONST_SRC_CODE_NEARPLANE_DX, zonetool::iw7::CONST_SRC_CODE_NEARPLANE_DX},
				{zonetool::h1::CONST_SRC_CODE_NEARPLANE_DY, zonetool::iw7::CONST_SRC_CODE_NEARPLANE_DY},
				{zonetool::h1::CONST_SRC_CODE_SSAO_POWER_BB_SHARPNESS_STEP, zonetool::iw7::CONST_SRC_CODE_SSAO_POWER_BB_SHARPNESS_STEP},
				{zonetool::h1::CONST_SRC_CODE_SSAO_COLOR_COEFF, zonetool::iw7::CONST_SRC_CODE_SSAO_COLOR_COEFF},
				{zonetool::h1::CONST_SRC_CODE_SSAO_FALLOFF_DEPTH_SCALE, zonetool::iw7::CONST_SRC_CODE_SSAO_FALLOFF_DEPTH_SCALE},
				{zonetool::h1::CONST_SRC_CODE_SSAO_UV_TO_ROT_SCALE_AND_FADE, zonetool::iw7::CONST_SRC_CODE_SSAO_UV_TO_ROT_SCALE_AND_FADE},
				{zonetool::h1::CONST_SRC_CODE_SSAO_SAMPLE_MAT_SCALE, zonetool::iw7::CONST_SRC_CODE_SSAO_SAMPLE_MAT_SCALE},
				{zonetool::h1::CONST_SRC_CODE_SSAO_DEPTH_OFFSET_REJECT, zonetool::iw7::CONST_SRC_CODE_SSAO_DEPTH_OFFSET_REJECT},
				{zonetool::h1::CONST_SRC_CODE_LIT2D_LIGHTDIRX2, zonetool::iw7::CONST_SRC_CODE_LIT2D_LIGHTDIRX2},
				{zonetool::h1::CONST_SRC_CODE_LIT2D_SPECHALFANGLEDIRX2, zonetool::iw7::CONST_SRC_CODE_LIT2D_SPECHALFANGLEDIRX2},
				{zonetool::h1::CONST_SRC_CODE_LIT2D_AMBIENTCOLOR, zonetool::iw7::CONST_SRC_CODE_LIT2D_AMBIENTCOLOR},
				{zonetool::h1::CONST_SRC_CODE_LIT2D_DIFFUSECOLOR, zonetool::iw7::CONST_SRC_CODE_LIT2D_DIFFUSECOLOR},
				{zonetool::h1::CONST_SRC_CODE_LIT2D_SPECCOLOR_SPECEXPONENT, zonetool::iw7::CONST_SRC_CODE_LIT2D_SPECCOLOR_SPECEXPONENT},
				{zonetool::h1::CONST_SRC_CODE_LIT2D_ADDITIVECOLOR, zonetool::iw7::CONST_SRC_CODE_LIT2D_ADDITIVECOLOR},
				{zonetool::h1::CONST_SRC_CODE_LIT2D_BLOODSPATTER_AMBIENTCOLOR, zonetool::iw7::CONST_SRC_CODE_LIT2D_BLOODSPATTER_AMBIENTCOLOR},
				{zonetool::h1::CONST_SRC_CODE_LIT2D_BLOODSPATTER_DIFFUSECOLOR, zonetool::iw7::CONST_SRC_CODE_LIT2D_BLOODSPATTER_DIFFUSECOLOR},
				{zonetool::h1::CONST_SRC_CODE_LIT2D_BLOODSPATTER_SPECCOLOR_SPECEXPONENT, zonetool::iw7::CONST_SRC_CODE_LIT2D_BLOODSPATTER_SPECCOLOR_SPECEXPONENT},
				{zonetool::h1::CONST_SRC_CODE_LIT2D_BLOODSPATTER_ADDITIVECOLOR, zonetool::iw7::CONST_SRC_CODE_LIT2D_BLOODSPATTER_ADDITIVECOLOR},
				//{zonetool::h1::CONST_SRC_CODE_LIT2D_HUDBLOOD_COLOR, zonetool::iw7::CONST_SRC_CODE_LIT2D_HUDBLOOD_COLOR},
				//{zonetool::h1::CONST_SRC_CODE_LIT2D_HUDBLOOD_COLOR_THIN, zonetool::iw7::CONST_SRC_CODE_LIT2D_HUDBLOOD_COLOR_THIN},
				{zonetool::h1::CONST_SRC_CODE_DOF_EQUATION_VIEWMODEL_AND_FAR_BLUR, zonetool::iw7::CONST_SRC_CODE_DOF_EQUATION_VIEWMODEL_AND_FAR_BLUR},
				{zonetool::h1::CONST_SRC_CODE_DOF_EQUATION_SCENE, zonetool::iw7::CONST_SRC_CODE_DOF_EQUATION_SCENE},
				{zonetool::h1::CONST_SRC_CODE_DOF_LERP_SCALE, zonetool::iw7::CONST_SRC_CODE_DOF_LERP_SCALE},
				{zonetool::h1::CONST_SRC_CODE_DOF_LERP_BIAS, zonetool::iw7::CONST_SRC_CODE_DOF_LERP_BIAS},
				{zonetool::h1::CONST_SRC_CODE_DOF_ROW_DELTA, zonetool::iw7::CONST_SRC_CODE_DOF_ROW_DELTA},
				//{zonetool::h1::CONST_SRC_CODE_DOF_EQUATION, zonetool::iw7::CONST_SRC_CODE_DOF_EQUATION},
				//{zonetool::h1::CONST_SRC_CODE_DOF_PARAMS, zonetool::iw7::CONST_SRC_CODE_DOF_PARAMS},
				//{/zonetool::h1::CONST_SRC_CODE_DOF_TILE_PARAMS, zonetool::iw7::CONST_SRC_CODE_DOF_TILE_PARAMS},
				//{zonetool::h1::CONST_SRC_CODE_FRAME_COUNT_PARAMS, zonetool::iw7::CONST_SRC_CODE_FRAME_COUNT_PARAMS},
				{zonetool::h1::CONST_SRC_CODE_MOTION_MATRIX_X, zonetool::iw7::CONST_SRC_CODE_MOTION_MATRIX_X},
				{zonetool::h1::CONST_SRC_CODE_MOTION_MATRIX_Y, zonetool::iw7::CONST_SRC_CODE_MOTION_MATRIX_Y},
				{zonetool::h1::CONST_SRC_CODE_MOTION_MATRIX_W, zonetool::iw7::CONST_SRC_CODE_MOTION_MATRIX_W},
				{zonetool::h1::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R0, zonetool::iw7::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R0},
				{zonetool::h1::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R1, zonetool::iw7::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R1},
				{zonetool::h1::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R2, zonetool::iw7::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R2},
				{zonetool::h1::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R3, zonetool::iw7::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R3},
				{zonetool::h1::CONST_SRC_CODE_PREV_EYEPOSITION_TRANSFORM, zonetool::iw7::CONST_SRC_CODE_PREV_EYEPOSITION_TRANSFORM},
				{zonetool::h1::CONST_SRC_CODE_SCREEN_SPACE_REFLECTION_PARAMETERS, zonetool::iw7::CONST_SRC_CODE_SCREEN_SPACE_REFLECTION_FADE }, //
				{zonetool::h1::CONST_SRC_CODE_CLIP_SPACE_LOOKUP_SCALE_AND_OFFSET, zonetool::iw7::CONST_SRC_CODE_CLIP_SPACE_LOOKUP_SCALE_AND_OFFSET},
				{zonetool::h1::CONST_SRC_CODE_SSR_CLIP_TO_FADE_SCALE_OFFSET_PS, zonetool::iw7::CONST_SRC_CODE_SSR_CLIP_TO_FADE_SCALE_OFFSET_PS},
				//{zonetool::h1::CONST_SRC_CODE_SSS_MRT_OFF_SHADER_OFF, zonetool::iw7::CONST_SRC_CODE_SSS_MRT_OFF_SHADER_OFF},
				//{zonetool::h1::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R0, zonetool::iw7::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R0},
				//{zonetool::h1::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R1, zonetool::iw7::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R1},
				//{zonetool::h1::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R2, zonetool::iw7::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R2},
				//{zonetool::h1::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R3, zonetool::iw7::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R3},
				//{zonetool::h1::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R0, zonetool::iw7::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R0},
				//{zonetool::h1::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R1, zonetool::iw7::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R1},
				//{zonetool::h1::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R2, zonetool::iw7::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R2},
				//{zonetool::h1::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R3, zonetool::iw7::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R3},
				//{zonetool::h1::CONST_SRC_CODE_MDAO_SCREEN_PARAMS, zonetool::iw7::CONST_SRC_CODE_MDAO_SCREEN_PARAMS},
				//{zonetool::h1::CONST_SRC_CODE_MDAO_CAMERA_PARAMS, zonetool::iw7::CONST_SRC_CODE_MDAO_CAMERA_PARAMS},
				//{zonetool::h1::CONST_SRC_CODE_MDAO_LOOKUP_PARAMS, zonetool::iw7::CONST_SRC_CODE_MDAO_LOOKUP_PARAMS},
				//{zonetool::h1::CONST_SRC_CODE_MDAO_VOLUME_PARAMS, zonetool::iw7::CONST_SRC_CODE_MDAO_VOLUME_PARAMS},
				{zonetool::h1::CONST_SRC_CODE_DISTORTION_SAMPLE_LIMITS_PS, zonetool::iw7::CONST_SRC_CODE_DISTORTION_SAMPLE_LIMITS_PS},
				{zonetool::h1::CONST_SRC_CODE_SCOPE_SAMPLE_LIMITS_PS, zonetool::iw7::CONST_SRC_CODE_SCOPE_SAMPLE_LIMITS_PS},
				//{zonetool::h1::CONST_SRC_CODE_UV_TO_PREV_SCALED_CLIP_MAT_C0_PS, zonetool::iw7::CONST_SRC_CODE_UV_TO_PREV_SCALED_CLIP_MAT_C0_PS},
				//{zonetool::h1::CONST_SRC_CODE_UV_TO_PREV_SCALED_CLIP_MAT_C1_PS, zonetool::iw7::CONST_SRC_CODE_UV_TO_PREV_SCALED_CLIP_MAT_C1_PS},
				//{zonetool::h1::CONST_SRC_CODE_UV_TO_PREV_SCALED_CLIP_MAT_C3_PS, zonetool::iw7::CONST_SRC_CODE_UV_TO_PREV_SCALED_CLIP_MAT_C3_PS},
				{zonetool::h1::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R0, zonetool::iw7::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R0},
				{zonetool::h1::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R1, zonetool::iw7::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R1},
				{zonetool::h1::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R2, zonetool::iw7::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R2},
				{zonetool::h1::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R3, zonetool::iw7::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R3},
				{zonetool::h1::CONST_SRC_CODE_PREV_FRAME_WORLD_MATRIX_EYE_OFFSET, zonetool::iw7::CONST_SRC_CODE_PREV_FRAME_WORLD_MATRIX_EYE_OFFSET},
				//{zonetool::h1::CONST_SRC_CODE_STATIC_VELOCITY_PARMS, zonetool::iw7::CONST_SRC_CODE_STATIC_VELOCITY_PARMS},
				{zonetool::h1::CONST_SRC_CODE_MOTION_BLUR_HQ_PARAMS, zonetool::iw7::CONST_SRC_CODE_MOTION_BLUR_HQ_PARAMS},
				{zonetool::h1::CONST_SRC_CODE_MOTION_BLUR_HQ_TILE_MAX_PARAMS, zonetool::iw7::CONST_SRC_CODE_MOTION_BLUR_HQ_TILE_MAX_PARAMS},
				{zonetool::h1::CONST_SRC_CODE_MB_UV_TO_PREV_SCALED_CLIP_MAT_C0_PS, zonetool::iw7::CONST_SRC_CODE_MB_UV_TO_PREV_SCALED_CLIP_MAT_C0_PS},
				{zonetool::h1::CONST_SRC_CODE_MB_UV_TO_PREV_SCALED_CLIP_MAT_C1_PS, zonetool::iw7::CONST_SRC_CODE_MB_UV_TO_PREV_SCALED_CLIP_MAT_C1_PS},
				{zonetool::h1::CONST_SRC_CODE_MB_UV_TO_PREV_SCALED_CLIP_MAT_C3_PS, zonetool::iw7::CONST_SRC_CODE_MB_UV_TO_PREV_SCALED_CLIP_MAT_C3_PS},
				//{zonetool::h1::CONST_SRC_CODE_SHADOWMAP_SWITCH_PARTITION_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_SHADOWMAP_SWITCH_PARTITION_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_SHADOWMAP_SWITCH_PARTITION_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_SHADOWMAP_SWITCH_PARTITION_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_SHADOWMAP_DISTANCE_BIAS, zonetool::iw7::CONST_SRC_CODE_SHADOWMAP_DISTANCE_BIAS},
				//{zonetool::h1::CONST_SRC_CODE_SHADOWMAP_SCALE, zonetool::iw7::CONST_SRC_CODE_SHADOWMAP_SCALE},
				//{zonetool::h1::CONST_SRC_CODE_SHADOWMAP_PARTITION_UV_OFFSET, zonetool::iw7::CONST_SRC_CODE_SHADOWMAP_PARTITION_UV_OFFSET},
				//{zonetool::h1::CONST_SRC_CODE_SHADOWMAP_CASCADE_MASK, zonetool::iw7::CONST_SRC_CODE_SHADOWMAP_CASCADE_MASK},
				//{zonetool::h1::CONST_SRC_CODE_SHADOWMAP_DISTANCE_BLEND, zonetool::iw7::CONST_SRC_CODE_SHADOWMAP_DISTANCE_BLEND},
				//{zonetool::h1::CONST_SRC_CODE_ZNEAR, zonetool::iw7::CONST_SRC_CODE_ZNEAR},
				{zonetool::h1::CONST_SRC_CODE_LIGHTING_LOOKUP_SCALE, zonetool::iw7::CONST_SRC_CODE_LIGHTING_LOOKUP_SCALE},
				{zonetool::h1::CONST_SRC_CODE_INV_SCENE_PROJECTION, zonetool::iw7::CONST_SRC_CODE_INV_SCENE_PROJECTION},
				//{zonetool::h1::CONST_SRC_CODE_RIM_LIGHT_0_DIR, zonetool::iw7::CONST_SRC_CODE_RIM_LIGHT_0_DIR},
				//{zonetool::h1::CONST_SRC_CODE_RIM_LIGHT_0_COLOR, zonetool::iw7::CONST_SRC_CODE_RIM_LIGHT_0_COLOR},
				//{zonetool::h1::CONST_SRC_CODE_RIM_LIGHT_1_DIR, zonetool::iw7::CONST_SRC_CODE_RIM_LIGHT_1_DIR},
				//{zonetool::h1::CONST_SRC_CODE_RIM_LIGHT_1_COLOR, zonetool::iw7::CONST_SRC_CODE_RIM_LIGHT_1_COLOR},
				//{zonetool::h1::CONST_SRC_CODE_RIM_LIGHT_TECHNIQUE, zonetool::iw7::CONST_SRC_CODE_RIM_LIGHT_TECHNIQUE},
				//{zonetool::h1::CONST_SRC_CODE_DEBUG_BUMPMAP, zonetool::iw7::CONST_SRC_CODE_DEBUG_BUMPMAP},
				{zonetool::h1::CONST_SRC_CODE_MATERIAL_COLOR, zonetool::iw7::CONST_SRC_CODE_MATERIAL_COLOR},
				{zonetool::h1::CONST_SRC_CODE_FOG, zonetool::iw7::CONST_SRC_CODE_FOG},
				{zonetool::h1::CONST_SRC_CODE_FOG_COLOR_LINEAR, zonetool::iw7::CONST_SRC_CODE_FOG_COLOR},
				//{zonetool::h1::CONST_SRC_CODE_FOG_COLOR_GAMMA, zonetool::iw7::CONST_SRC_CODE_FOG_COLOR_GAMMA},
				{zonetool::h1::CONST_SRC_CODE_FOG_SUN_CONSTS, zonetool::iw7::CONST_SRC_CODE_FOG_SUN_CONSTS},
				{zonetool::h1::CONST_SRC_CODE_FOG_SUN_COLOR_LINEAR, zonetool::iw7::CONST_SRC_CODE_FOG_SUN_COLOR},
				//{zonetool::h1::CONST_SRC_CODE_FOG_SUN_COLOR_GAMMA, zonetool::iw7::CONST_SRC_CODE_FOG_SUN_COLOR_GAMMA},
				{zonetool::h1::CONST_SRC_CODE_FOG_SUN_DIR, zonetool::iw7::CONST_SRC_CODE_FOG_SUN_DIR},
				//{zonetool::h1::CONST_SRC_CODE_FOG_SKY_FOG, zonetool::iw7::CONST_SRC_CODE_FOG_SKY_FOG},
				{zonetool::h1::CONST_SRC_CODE_FOG_HEIGHT_FOG, zonetool::iw7::CONST_SRC_CODE_FOG_HEIGHT },
				//{zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_0, zonetool::iw7::CONST_SRC_CODE_ATMOS_FOG_PARMS_0},
				//{zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_1, zonetool::iw7::CONST_SRC_CODE_ATMOS_FOG_PARMS_1},
				//{zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_2, zonetool::iw7::CONST_SRC_CODE_ATMOS_FOG_PARMS_2},
				//{zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_3, zonetool::iw7::CONST_SRC_CODE_ATMOS_FOG_PARMS_3},
				//{zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_4, zonetool::iw7::CONST_SRC_CODE_ATMOS_FOG_PARMS_4},
				//{zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_5, zonetool::iw7::CONST_SRC_CODE_ATMOS_FOG_PARMS_5},
				//{zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_6, zonetool::iw7::CONST_SRC_CODE_ATMOS_FOG_PARMS_6},
				//{zonetool::h1::CONST_SRC_CODE_FOG_SKY_DIR, zonetool::iw7::CONST_SRC_CODE_FOG_SKY_DIR},
				//{zonetool::h1::CONST_SRC_CODE_FOG_DEPTHHACK, zonetool::iw7::CONST_SRC_CODE_FOG_DEPTHHACK},
				//{zonetool::h1::CONST_SRC_CODE_GLOW_SETUP, zonetool::iw7::CONST_SRC_CODE_GLOW_SETUP},
				//{zonetool::h1::CONST_SRC_CODE_GLOW_APPLY, zonetool::iw7::CONST_SRC_CODE_GLOW_APPLY},
				//{zonetool::h1::CONST_SRC_CODE_GLOW_SETUP_ALT_COLOR_SCALE, zonetool::iw7::CONST_SRC_CODE_GLOW_SETUP_ALT_COLOR_SCALE},
				//{zonetool::h1::CONST_SRC_CODE_COLOR_BIAS, zonetool::iw7::CONST_SRC_CODE_COLOR_BIAS},
				//{zonetool::h1::CONST_SRC_CODE_COLOR_TINT_BASE, zonetool::iw7::CONST_SRC_CODE_COLOR_TINT_BASE},
				//{zonetool::h1::CONST_SRC_CODE_COLOR_TINT_DELTA, zonetool::iw7::CONST_SRC_CODE_COLOR_TINT_DELTA},
				//{zonetool::h1::CONST_SRC_CODE_COLOR_TINT_QUADRATIC_DELTA, zonetool::iw7::CONST_SRC_CODE_COLOR_TINT_QUADRATIC_DELTA},
				{zonetool::h1::CONST_SRC_CODE_PERCEPTUAL_PARMS, zonetool::iw7::CONST_SRC_CODE_PERCEPTUAL_PARMS},
				//{zonetool::h1::CONST_SRC_CODE_FILMIC_PARMS, zonetool::iw7::CONST_SRC_CODE_FILMIC_PARMS},
				//{zonetool::h1::CONST_SRC_CODE_FILMIC_SHOULDER_PARMS, zonetool::iw7::CONST_SRC_CODE_FILMIC_SHOULDER_PARMS},
				//{zonetool::h1::CONST_SRC_CODE_FILMIC_TOE_PARMS, zonetool::iw7::CONST_SRC_CODE_FILMIC_TOE_PARMS},
				{zonetool::h1::CONST_SRC_CODE_TONEMAP_PARMS, zonetool::iw7::CONST_SRC_CODE_TONEMAP_PARMS},
				//{zonetool::h1::CONST_SRC_CODE_HDR_STAGE_PARMS, zonetool::iw7::CONST_SRC_CODE_HDR_STAGE_PARMS},
				//{zonetool::h1::CONST_SRC_CODE_UI3D_UV_SETUP_0, zonetool::iw7::CONST_SRC_CODE_UI3D_UV_SETUP_0},
				//{zonetool::h1::CONST_SRC_CODE_UI3D_UV_SETUP_1, zonetool::iw7::CONST_SRC_CODE_UI3D_UV_SETUP_1},
				//{zonetool::h1::CONST_SRC_CODE_UI3D_UV_SETUP_2, zonetool::iw7::CONST_SRC_CODE_UI3D_UV_SETUP_2},
				//{zonetool::h1::CONST_SRC_CODE_UI3D_UV_SETUP_3, zonetool::iw7::CONST_SRC_CODE_UI3D_UV_SETUP_3},
				//{zonetool::h1::CONST_SRC_CODE_UI3D_UV_SETUP_4, zonetool::iw7::CONST_SRC_CODE_UI3D_UV_SETUP_4},
				//{zonetool::h1::CONST_SRC_CODE_UI3D_UV_SETUP_5, zonetool::iw7::CONST_SRC_CODE_UI3D_UV_SETUP_5},
				//{zonetool::h1::CONST_SRC_CODE_HUDFX_PARMS, zonetool::iw7::CONST_SRC_CODE_HUDFX_PARMS},
				//{zonetool::h1::CONST_SRC_CODE_HUDFX_PARMS2, zonetool::iw7::CONST_SRC_CODE_HUDFX_PARMS2},
				{zonetool::h1::CONST_SRC_CODE_SSSS_PARAMS, zonetool::iw7::CONST_SRC_CODE_SSSS_PARAMS},
				{zonetool::h1::CONST_SRC_CODE_SSSS_SCALE, zonetool::iw7::CONST_SRC_CODE_SSSS_SCALE},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_0, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_0},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_1, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_1},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_2, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_2},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_3, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_3},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_4, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_4},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_5, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_5},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_6, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_6},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_7, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_7},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_8, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_8},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_9, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_9},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_10, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_10},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_11, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_11},
				//{zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_12, zonetool::iw7::CONST_SRC_CODE_SSSS_KERNEL_12},
				{zonetool::h1::CONST_SRC_CODE_OUTDOOR_FEATHER_PARMS, zonetool::iw7::CONST_SRC_CODE_OUTDOOR_FEATHER_PARMS},
				//{zonetool::h1::CONST_SRC_CODE_ENVMAP_PARMS, zonetool::iw7::CONST_SRC_CODE_ENVMAP_PARMS},
				//{zonetool::h1::CONST_SRC_CODE_SUN_SHADOWMAP_PIXEL_ADJUST_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_SUN_SHADOWMAP_PIXEL_ADJUST_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_SUN_SHADOWMAP_PIXEL_ADJUST_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_SUN_SHADOWMAP_PIXEL_ADJUST_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_SUN_SHADOWMAP_PIXEL_ADJUST_ARRAY_2, zonetool::iw7::CONST_SRC_CODE_SUN_SHADOWMAP_PIXEL_ADJUST_ARRAY_2},
				//{zonetool::h1::CONST_SRC_CODE_SUN_SHADOWMAP_CASCADE_V_CLAMP, zonetool::iw7::CONST_SRC_CODE_SUN_SHADOWMAP_CASCADE_V_CLAMP},
				//{zonetool::h1::CONST_SRC_CODE_SUN_SHADOWMAP_NEAR_FAR_PLANE, zonetool::iw7::CONST_SRC_CODE_SUN_SHADOWMAP_NEAR_FAR_PLANE},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_1, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_1},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_2, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_2},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_3, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_3},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_2, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_2},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_3, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_3},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_1, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_1},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_2, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_2},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_3, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_3},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_0, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_0},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_1, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_1},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_2, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_2},
				//{zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_3, zonetool::iw7::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_3},
				//{zonetool::h1::CONST_SRC_CODE_COMPOSITE_FX_DISTORTION, zonetool::iw7::CONST_SRC_CODE_COMPOSITE_FX_DISTORTION},
				//{zonetool::h1::CONST_SRC_CODE_POSTFX_FADE_EFFECT, zonetool::iw7::CONST_SRC_CODE_POSTFX_FADE_EFFECT},
				//{zonetool::h1::CONST_SRC_CODE_SCENE_UV_MULT, zonetool::iw7::CONST_SRC_CODE_SCENE_UV_MULT},
				//{zonetool::h1::CONST_SRC_CODE_SCENE_VIEW_MULT, zonetool::iw7::CONST_SRC_CODE_SCENE_VIEW_MULT},
				//{zonetool::h1::CONST_SRC_CODE_TEXCOORD_CLAMP_0, zonetool::iw7::CONST_SRC_CODE_TEXCOORD_CLAMP_0},
				//{zonetool::h1::CONST_SRC_CODE_TEXCOORD_CLAMP_1, zonetool::iw7::CONST_SRC_CODE_TEXCOORD_CLAMP_1},
				{zonetool::h1::CONST_SRC_CODE_VIEWPORT_DIMENSIONS, zonetool::iw7::CONST_SRC_CODE_VIEWPORT_DIMENSIONS},
				{zonetool::h1::CONST_SRC_CODE_FRAMEBUFFER_READ, zonetool::iw7::CONST_SRC_CODE_FRAMEBUFFER_READ},
				//{zonetool::h1::CONST_SRC_CODE_THERMAL_COLOR_OFFSET, zonetool::iw7::CONST_SRC_CODE_THERMAL_COLOR_OFFSET},
				{zonetool::h1::CONST_SRC_CODE_THERMAL_FADE_CONTROL, zonetool::iw7::CONST_SRC_CODE_THERMAL_FADE_CONTROL},
				{zonetool::h1::CONST_SRC_CODE_THERMAL_FADE_COLOR, zonetool::iw7::CONST_SRC_CODE_THERMAL_FADE_COLOR},
				{zonetool::h1::CONST_SRC_CODE_PLAYLIST_POPULATION_PARAMS, zonetool::iw7::CONST_SRC_CODE_PLAYLIST_POPULATION_PARAMS},
				{zonetool::h1::CONST_SRC_CODE_TESSELLATION_PARMS, zonetool::iw7::CONST_SRC_CODE_TESSELLATION_PARMS},
				{zonetool::h1::CONST_SRC_CODE_TESSELLATION_PARMS2, zonetool::iw7::CONST_SRC_CODE_TESSELLATION_PARMS2},
				//{zonetool::h1::CONST_SRC_CODE_EYE_PARAMETER_DVAR, zonetool::iw7::CONST_SRC_CODE_EYE_PARAMETER_DVAR},
				//{zonetool::h1::CONST_SRC_CODE_MP_RIM_PARAMETER_DVAR1, zonetool::iw7::CONST_SRC_CODE_MP_RIM_PARAMETER_DVAR1},
				//{zonetool::h1::CONST_SRC_CODE_MP_RIM_PARAMETER_DVAR2, zonetool::iw7::CONST_SRC_CODE_MP_RIM_PARAMETER_DVAR2},
				//{zonetool::h1::CONST_SRC_CODE_HEAD_ROT_MAT_R0, zonetool::iw7::CONST_SRC_CODE_HEAD_ROT_MAT_R0},
				//{zonetool::h1::CONST_SRC_CODE_HEAD_ROT_MAT_R1, zonetool::iw7::CONST_SRC_CODE_HEAD_ROT_MAT_R1},
				//{zonetool::h1::CONST_SRC_CODE_HEAD_ROT_MAT_R2, zonetool::iw7::CONST_SRC_CODE_HEAD_ROT_MAT_R2},
				//{zonetool::h1::CONST_SRC_CODE_GUN_SIGHT_COLOR, zonetool::iw7::CONST_SRC_CODE_GUN_SIGHT_COLOR},
				//{zonetool::h1::CONST_SRC_CODE_GUN_RETICLE_COLOR, zonetool::iw7::CONST_SRC_CODE_GUN_RETICLE_COLOR},
				{zonetool::h1::CONST_SRC_CODE_BASE_LIGHTING_COORDS, zonetool::iw7::CONST_SRC_CODE_BASE_LIGHTING_COORDS},
				//{zonetool::h1::CONST_SRC_CODE_LIGHT_PROBE_AMBIENT, zonetool::iw7::CONST_SRC_CODE_LIGHT_PROBE_AMBIENT},
				{zonetool::h1::CONST_SRC_CODE_CLIP_SPACE_LOOKUP_SCALE, zonetool::iw7::CONST_SRC_CODE_CLIP_SPACE_LOOKUP_SCALE},
				{zonetool::h1::CONST_SRC_CODE_CLIP_SPACE_LOOKUP_OFFSET, zonetool::iw7::CONST_SRC_CODE_CLIP_SPACE_LOOKUP_OFFSET},
				//{zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_TEXTURE_ATLAS_SETTINGS, zonetool::iw7::CONST_SRC_CODE_PARTICLE_CLOUD_TEXTURE_ATLAS_SETTINGS},
				//{zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_VEL_WORLD, zonetool::iw7::CONST_SRC_CODE_PARTICLE_CLOUD_VEL_WORLD},
				{zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_MATRIX0, zonetool::iw7::CONST_SRC_CODE_PARTICLE_CLOUD_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_MATRIX1, zonetool::iw7::CONST_SRC_CODE_PARTICLE_CLOUD_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_MATRIX2, zonetool::iw7::CONST_SRC_CODE_PARTICLE_CLOUD_MATRIX2},
				{zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_SPARK_COLOR0, zonetool::iw7::CONST_SRC_CODE_PARTICLE_CLOUD_SPARK_COLOR0},
				{zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_SPARK_COLOR1, zonetool::iw7::CONST_SRC_CODE_PARTICLE_CLOUD_SPARK_COLOR1},
				{zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_SPARK_COLOR2, zonetool::iw7::CONST_SRC_CODE_PARTICLE_CLOUD_SPARK_COLOR2},
				{zonetool::h1::CONST_SRC_CODE_PARTICLE_FOUNTAIN_PARM0, zonetool::iw7::CONST_SRC_CODE_PARTICLE_FOUNTAIN_PARM0},
				{zonetool::h1::CONST_SRC_CODE_PARTICLE_FOUNTAIN_PARM1, zonetool::iw7::CONST_SRC_CODE_PARTICLE_FOUNTAIN_PARM1},
				{zonetool::h1::CONST_SRC_CODE_LIT2D_BLOODSPATTER_FADESHARPNESS, zonetool::iw7::CONST_SRC_CODE_LIT2D_BLOODSPATTER_FADESHARPNESS},
				{zonetool::h1::CONST_SRC_CODE_BLUR_SCENE_PIXEL_POS_TO_UV, zonetool::iw7::CONST_SRC_CODE_BLUR_SCENE_PIXEL_POS_TO_UV},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_0, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_0},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_1, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_1},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_2, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_2},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_3, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_3},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_4, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_4},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_5, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_5},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_6, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_6},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_7, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_7},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_8, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_8},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_9, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_9},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_10, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_10},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_11, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_11},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_12, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_12},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_13, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_13},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_14, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_14},
				{zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_15, zonetool::iw7::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_15},
				{zonetool::h1::CONST_SRC_CODE_DEPTH_FROM_CLIP, zonetool::iw7::CONST_SRC_CODE_DEPTH_FROM_CLIP},
				{zonetool::h1::CONST_SRC_CODE_CODE_MESH_ARG_0, zonetool::iw7::CONST_SRC_CODE_CODE_MESH_ARG_0},
				{zonetool::h1::CONST_SRC_CODE_CODE_MESH_ARG_1, zonetool::iw7::CONST_SRC_CODE_CODE_MESH_ARG_1},
				{zonetool::h1::CONST_SRC_CODE_CODE_MESH_ARG_3, zonetool::iw7::CONST_SRC_CODE_CODE_MESH_ARG_3},
				{zonetool::h1::CONST_SRC_CODE_CODE_MESH_ARG_4, zonetool::iw7::CONST_SRC_CODE_CODE_MESH_ARG_4},
				//{zonetool::h1::CONST_SRC_CODE_SCRIPT_CONST0, zonetool::iw7::CONST_SRC_CODE_SCRIPT_CONST0},
				{zonetool::h1::CONST_SRC_CODE_VIEW_MATRIX, zonetool::iw7::CONST_SRC_CODE_VIEW_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_VIEW_MATRIX, zonetool::iw7::CONST_SRC_CODE_INVERSE_VIEW_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_VIEW_MATRIX, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_VIEW_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_VIEW_MATRIX, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_VIEW_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_PROJECTION_MATRIX, zonetool::iw7::CONST_SRC_CODE_PROJECTION_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_PROJECTION_MATRIX, zonetool::iw7::CONST_SRC_CODE_INVERSE_PROJECTION_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_PROJECTION_MATRIX, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_PROJECTION_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_PROJECTION_MATRIX, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_PROJECTION_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_VIEW_PROJECTION_MATRIX, zonetool::iw7::CONST_SRC_CODE_VIEW_PROJECTION_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_VIEW_PROJECTION_MATRIX, zonetool::iw7::CONST_SRC_CODE_INVERSE_VIEW_PROJECTION_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_VIEW_PROJECTION_MATRIX, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_VIEW_PROJECTION_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_VIEW_PROJECTION_MATRIX, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_VIEW_PROJECTION_MATRIX},
				//{zonetool::h1::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX, zonetool::iw7::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX},
				//{zonetool::h1::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX, zonetool::iw7::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX},
				//{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX},
				//{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX},
				//{zonetool::h1::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX1, zonetool::iw7::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX1},
				//{zonetool::h1::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX1, zonetool::iw7::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX1},
				//{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX1, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX1},
				//{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX1, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX1},
				//{zonetool::h1::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX2, zonetool::iw7::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX2},
				//{zonetool::h1::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX2, zonetool::iw7::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX2},
				//{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX2, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX2},
				//{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX2, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX2},
				//{zonetool::h1::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX3, zonetool::iw7::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX3},
				//{zonetool::h1::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX3, zonetool::iw7::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX3},
				//{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX3, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX3},
				//{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX3, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX3},
				{zonetool::h1::CONST_SRC_CODE_WORLD_OUTDOOR_LOOKUP_MATRIX, zonetool::iw7::CONST_SRC_CODE_WORLD_OUTDOOR_LOOKUP_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_OUTDOOR_LOOKUP_MATRIX, zonetool::iw7::CONST_SRC_CODE_INVERSE_WORLD_OUTDOOR_LOOKUP_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_OUTDOOR_LOOKUP_MATRIX, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_WORLD_OUTDOOR_LOOKUP_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_OUTDOOR_LOOKUP_MATRIX, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_OUTDOOR_LOOKUP_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_PREV_FRAME_WORLD_MATRIX, zonetool::iw7::CONST_SRC_CODE_PREV_FRAME_WORLD_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_PREV_FRAME_INVERSE_WORLD_MATRIX, zonetool::iw7::CONST_SRC_CODE_PREV_FRAME_INVERSE_WORLD_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_PREV_FRAME_TRANSPOSE_WORLD_MATRIX, zonetool::iw7::CONST_SRC_CODE_PREV_FRAME_TRANSPOSE_WORLD_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_PREV_FRAME_INVERSE_TRANSPOSE_WORLD_MATRIX, zonetool::iw7::CONST_SRC_CODE_PREV_FRAME_INVERSE_TRANSPOSE_WORLD_MATRIX},
				{zonetool::h1::CONST_SRC_CODE_WORLD_MATRIX0, zonetool::iw7::CONST_SRC_CODE_WORLD_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_MATRIX0, zonetool::iw7::CONST_SRC_CODE_INVERSE_WORLD_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_MATRIX0, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_WORLD_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_MATRIX0, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_WORLD_VIEW_MATRIX0, zonetool::iw7::CONST_SRC_CODE_WORLD_VIEW_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_VIEW_MATRIX0, zonetool::iw7::CONST_SRC_CODE_INVERSE_WORLD_VIEW_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_MATRIX0, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_MATRIX0, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_WORLD_VIEW_PROJECTION_MATRIX0, zonetool::iw7::CONST_SRC_CODE_WORLD_VIEW_PROJECTION_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_VIEW_PROJECTION_MATRIX0, zonetool::iw7::CONST_SRC_CODE_INVERSE_WORLD_VIEW_PROJECTION_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX0, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX0, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX0},
				{zonetool::h1::CONST_SRC_CODE_WORLD_MATRIX1, zonetool::iw7::CONST_SRC_CODE_WORLD_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_MATRIX1, zonetool::iw7::CONST_SRC_CODE_INVERSE_WORLD_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_MATRIX1, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_WORLD_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_MATRIX1, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_WORLD_VIEW_MATRIX1, zonetool::iw7::CONST_SRC_CODE_WORLD_VIEW_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_VIEW_MATRIX1, zonetool::iw7::CONST_SRC_CODE_INVERSE_WORLD_VIEW_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_MATRIX1, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_MATRIX1, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_WORLD_VIEW_PROJECTION_MATRIX1, zonetool::iw7::CONST_SRC_CODE_WORLD_VIEW_PROJECTION_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_VIEW_PROJECTION_MATRIX1, zonetool::iw7::CONST_SRC_CODE_INVERSE_WORLD_VIEW_PROJECTION_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX1, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX1, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX1},
				{zonetool::h1::CONST_SRC_CODE_WORLD_MATRIX2, zonetool::iw7::CONST_SRC_CODE_WORLD_MATRIX2},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_MATRIX2, zonetool::iw7::CONST_SRC_CODE_INVERSE_WORLD_MATRIX2},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_MATRIX2, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_WORLD_MATRIX2},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_MATRIX2, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_MATRIX2},
				{zonetool::h1::CONST_SRC_CODE_WORLD_VIEW_MATRIX2, zonetool::iw7::CONST_SRC_CODE_WORLD_VIEW_MATRIX2},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_VIEW_MATRIX2, zonetool::iw7::CONST_SRC_CODE_INVERSE_WORLD_VIEW_MATRIX2},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_MATRIX2, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_MATRIX2},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_MATRIX2, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_MATRIX2},
				{zonetool::h1::CONST_SRC_CODE_WORLD_VIEW_PROJECTION_MATRIX2, zonetool::iw7::CONST_SRC_CODE_WORLD_VIEW_PROJECTION_MATRIX2},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_VIEW_PROJECTION_MATRIX2, zonetool::iw7::CONST_SRC_CODE_INVERSE_WORLD_VIEW_PROJECTION_MATRIX2},
				{zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX2, zonetool::iw7::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX2},
				{zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX2, zonetool::iw7::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX2},
				{zonetool::h1::CONST_SRC_TOTAL_COUNT, zonetool::iw7::CONST_SRC_TOTAL_COUNT},
				{zonetool::h1::CONST_SRC_NONE, zonetool::iw7::CONST_SRC_NONE},
			};

			const std::unordered_map <std::uint32_t, std::uint32_t> texture_src_code_map =
			{
				{zonetool::h1::TEXTURE_SRC_CODE_BLACK, zonetool::iw7::TEXTURE_SRC_CODE_BLACK},
				{zonetool::h1::TEXTURE_SRC_CODE_WHITE, zonetool::iw7::TEXTURE_SRC_CODE_WHITE},
				{zonetool::h1::TEXTURE_SRC_CODE_IDENTITY_NORMAL_MAP, zonetool::iw7::TEXTURE_SRC_CODE_IDENTITY_NORMAL_MAP},
				{zonetool::h1::TEXTURE_SRC_CODE_MODEL_LIGHTING, zonetool::iw7::TEXTURE_SRC_CODE_MODEL_LIGHTING},
				{zonetool::h1::TEXTURE_SRC_CODE_LIGHTMAP_PRIMARY, zonetool::iw7::TEXTURE_SRC_CODE_LIGHTMAP_PRIMARY},
				{zonetool::h1::TEXTURE_SRC_CODE_LIGHTMAP_SECONDARY, zonetool::iw7::TEXTURE_SRC_CODE_LIGHTMAP_SECONDARY},
				//{zonetool::h1::TEXTURE_SRC_CODE_SHADOWMAP_SUN, zonetool::iw7::TEXTURE_SRC_CODE_SHADOWMAP_SUN},
				//{zonetool::h1::TEXTURE_SRC_CODE_TRANS_SHADOWMAP_SUN, zonetool::iw7::TEXTURE_SRC_CODE_TRANS_SHADOWMAP_SUN},
				//{zonetool::h1::TEXTURE_SRC_CODE_SHADOWMAP_SPOT, zonetool::iw7::TEXTURE_SRC_CODE_SHADOWMAP_SPOT},
				//{zonetool::h1::TEXTURE_SRC_CODE_SHADOWMAP_SPOT_1, zonetool::iw7::TEXTURE_SRC_CODE_SHADOWMAP_SPOT_1},
				//{zonetool::h1::TEXTURE_SRC_CODE_SHADOWMAP_SPOT_2, zonetool::iw7::TEXTURE_SRC_CODE_SHADOWMAP_SPOT_2},
				//{zonetool::h1::TEXTURE_SRC_CODE_SHADOWMAP_SPOT_3, zonetool::iw7::TEXTURE_SRC_CODE_SHADOWMAP_SPOT_3},
				{zonetool::h1::TEXTURE_SRC_CODE_FEEDBACK, zonetool::iw7::TEXTURE_SRC_CODE_FEEDBACK},
				//{zonetool::h1::TEXTURE_SRC_CODE_RESOLVED_POST_SUN, zonetool::iw7::TEXTURE_SRC_CODE_RESOLVED_POST_SUN},
				//{zonetool::h1::TEXTURE_SRC_CODE_SSR_BUFFER, zonetool::iw7::TEXTURE_SRC_CODE_SSR_BUFFER},
				//{zonetool::h1::TEXTURE_SRC_CODE_HQ_SSR_DEPTH, zonetool::iw7::TEXTURE_SRC_CODE_HQ_SSR_DEPTH},
				//{zonetool::h1::TEXTURE_SRC_CODE_BLUR_DISTORTION_BUFFER,	zonetool::iw7::TEXTURE_SRC_CODE_BLUR_DISTORTION_BUFFER},
				{zonetool::h1::TEXTURE_SRC_CODE_RESOLVED_SCENE, zonetool::iw7::TEXTURE_SRC_CODE_RESOLVED_SCENE},
				{zonetool::h1::TEXTURE_SRC_CODE_POST_EFFECT_0, zonetool::iw7::TEXTURE_SRC_CODE_POST_EFFECT_0},
				{zonetool::h1::TEXTURE_SRC_CODE_POST_EFFECT_1, zonetool::iw7::TEXTURE_SRC_CODE_POST_EFFECT_1},
				{zonetool::h1::TEXTURE_SRC_CODE_LIGHT_ATTENUATION, zonetool::iw7::TEXTURE_SRC_CODE_LIGHT_ATTENUATION},
				//{zonetool::h1::TEXTURE_SRC_CODE_LIGHT_CUCOLORIS, zonetool::iw7::TEXTURE_SRC_CODE_LIGHT_CUCOLORIS},
				//{zonetool::h1::TEXTURE_SRC_CODE_LIGHT_ATTENUATION1, zonetool::iw7::TEXTURE_SRC_CODE_LIGHT_ATTENUATION1},
				//{zonetool::h1::TEXTURE_SRC_CODE_LIGHT_CUCOLORIS1, zonetool::iw7::TEXTURE_SRC_CODE_LIGHT_CUCOLORIS1},
				//{zonetool::h1::TEXTURE_SRC_CODE_LIGHT_ATTENUATION2, zonetool::iw7::TEXTURE_SRC_CODE_LIGHT_ATTENUATION2},
				//{zonetool::h1::TEXTURE_SRC_CODE_LIGHT_CUCOLORIS2, zonetool::iw7::TEXTURE_SRC_CODE_LIGHT_CUCOLORIS2},
				//{zonetool::h1::TEXTURE_SRC_CODE_LIGHT_ATTENUATION3, zonetool::iw7::TEXTURE_SRC_CODE_LIGHT_ATTENUATION3},
				//{zonetool::h1::TEXTURE_SRC_CODE_LIGHT_CUCOLORIS3, zonetool::iw7::TEXTURE_SRC_CODE_LIGHT_CUCOLORIS3},
				{zonetool::h1::TEXTURE_SRC_CODE_OUTDOOR, zonetool::iw7::TEXTURE_SRC_CODE_OUTDOOR},
				{zonetool::h1::TEXTURE_SRC_CODE_FLOATZ, zonetool::iw7::TEXTURE_SRC_CODE_FLOATZ},
				//{zonetool::h1::TEXTURE_SRC_CODE_PROCESSED_FLOATZ, zonetool::iw7::TEXTURE_SRC_CODE_PROCESSED_FLOATZ},
				{zonetool::h1::TEXTURE_SRC_CODE_RAW_FLOATZ, zonetool::iw7::TEXTURE_SRC_CODE_RAW_FLOATZ},
				//{zonetool::h1::TEXTURE_SRC_CODE_FLOATZ_STENCIL, zonetool::iw7::TEXTURE_SRC_CODE_FLOATZ_STENCIL},
				{zonetool::h1::TEXTURE_SRC_CODE_RAW_STENCIL, zonetool::iw7::TEXTURE_SRC_CODE_RAW_STENCIL},
				//{zonetool::h1::TEXTURE_SRC_CODE_HALF_PARTICLES, zonetool::iw7::TEXTURE_SRC_CODE_HALF_PARTICLES},
				//{zonetool::h1::TEXTURE_SRC_CODE_HALF_PARTICLES_Z, zonetool::iw7::TEXTURE_SRC_CODE_HALF_PARTICLES_Z},
				{zonetool::h1::TEXTURE_SRC_CODE_CASE_TEXTURE, zonetool::iw7::TEXTURE_SRC_CODE_CASE_TEXTURE},
				{zonetool::h1::TEXTURE_SRC_CODE_CINEMATIC_Y, zonetool::iw7::TEXTURE_SRC_CODE_CINEMATIC_Y},
				{zonetool::h1::TEXTURE_SRC_CODE_CINEMATIC_CR, zonetool::iw7::TEXTURE_SRC_CODE_CINEMATIC_CR},
				{zonetool::h1::TEXTURE_SRC_CODE_CINEMATIC_CB, zonetool::iw7::TEXTURE_SRC_CODE_CINEMATIC_CB},
				{zonetool::h1::TEXTURE_SRC_CODE_CINEMATIC_A, zonetool::iw7::TEXTURE_SRC_CODE_CINEMATIC_A},
				{zonetool::h1::TEXTURE_SRC_CODE_CINEMATIC_CBCR, zonetool::iw7::TEXTURE_SRC_CODE_CINEMATIC_CBCR},
				{zonetool::h1::TEXTURE_SRC_CODE_REFLECTION_PROBE, zonetool::iw7::TEXTURE_SRC_CODE_REFLECTION_PROBE},
				//{zonetool::h1::TEXTURE_SRC_CODE_DALTONIZE_CLUT, zonetool::iw7::TEXTURE_SRC_CODE_DALTONIZE_CLUT},
				//{zonetool::h1::TEXTURE_SRC_CODE_CLUT, zonetool::iw7::TEXTURE_SRC_CODE_CLUT},
				{zonetool::h1::TEXTURE_SRC_CODE_LINEAR_CLAMP, zonetool::iw7::TEXTURE_SRC_CODE_LINEAR_CLAMP},
				{zonetool::h1::TEXTURE_SRC_CODE_POINT_CLAMP, zonetool::iw7::TEXTURE_SRC_CODE_POINT_CLAMP},
				//{zonetool::h1::TEXTURE_SRC_CODE_BLUR_SCENE_SAVE, zonetool::iw7::TEXTURE_SRC_CODE_BLUR_SCENE_SAVE},
				//{zonetool::h1::TEXTURE_SRC_CODE_RANDOM_ROTATIONS, zonetool::iw7::TEXTURE_SRC_CODE_RANDOM_ROTATIONS},
				{zonetool::h1::TEXTURE_SRC_CODE_SSAO, zonetool::iw7::TEXTURE_SRC_CODE_SSAO},
				{zonetool::h1::TEXTURE_SRC_CODE_POSTFX_TEXTURE_0, zonetool::iw7::TEXTURE_SRC_CODE_POSTFX_TEXTURE_0},
				{zonetool::h1::TEXTURE_SRC_CODE_POSTFX_TEXTURE_1, zonetool::iw7::TEXTURE_SRC_CODE_POSTFX_TEXTURE_1},
				{zonetool::h1::TEXTURE_SRC_CODE_POSTFX_TEXTURE_2, zonetool::iw7::TEXTURE_SRC_CODE_POSTFX_TEXTURE_2},
				{zonetool::h1::TEXTURE_SRC_CODE_POSTFX_TEXTURE_3, zonetool::iw7::TEXTURE_SRC_CODE_POSTFX_TEXTURE_3},
				//{zonetool::h1::TEXTURE_SRC_CODE_MSAA_SCENE, zonetool::iw7::TEXTURE_SRC_CODE_MSAA_SCENE},
				{zonetool::h1::TEXTURE_SRC_CODE_DEPTH_BLUR_0, zonetool::iw7::TEXTURE_SRC_CODE_DEPTH_BLUR_0},
				{zonetool::h1::TEXTURE_SRC_CODE_DEPTH_BLUR_1, zonetool::iw7::TEXTURE_SRC_CODE_DEPTH_BLUR_1},
				//{zonetool::h1::TEXTURES_SRC_CODE_DEFAULT_DEPTH, zonetool::iw7::TEXTURES_SRC_CODE_DEFAULT_DEPTH},
				{zonetool::h1::TEXTURE_SRC_CODE_SCENE_VELOCITY, zonetool::iw7::TEXTURE_SRC_CODE_SCENE_VELOCITY},
				//{zonetool::h1::TEXTURE_SRC_CODE_SCENE_VELOCITY_TILE0, zonetool::iw7::TEXTURE_SRC_CODE_SCENE_VELOCITY_TILE0},
				//{zonetool::h1::TEXTURE_SRC_CODE_SCENE_VELOCITY_TILE1, zonetool::iw7::TEXTURE_SRC_CODE_SCENE_VELOCITY_TILE1},
				//{zonetool::h1::TEXTURE_SRC_CODE_DOF_FLOATZ, zonetool::iw7::TEXTURE_SRC_CODE_DOF_FLOATZ},
				//{zonetool::h1::TEXTURE_SRC_CODE_DOF_HALF_PREPASS, zonetool::iw7::TEXTURE_SRC_CODE_DOF_HALF_PREPASS},
				//{zonetool::h1::TEXTURE_SRC_CODE_DOF_HALF_COLOR, zonetool::iw7::TEXTURE_SRC_CODE_DOF_HALF_COLOR},
				//{zonetool::h1::TEXTURE_SRC_CODE_DOF_HALF_ALPHA, zonetool::iw7::TEXTURE_SRC_CODE_DOF_HALF_ALPHA},
				//{zonetool::h1::TEXTURE_SRC_CODE_DOF_TILE0, zonetool::iw7::TEXTURE_SRC_CODE_DOF_TILE0},
				//{zonetool::h1::TEXTURE_SRC_CODE_DOF_TILE1, zonetool::iw7::TEXTURE_SRC_CODE_DOF_TILE1},
				{zonetool::h1::TEXTURE_SRC_CODE_SCENE_SPECULAR, zonetool::iw7::TEXTURE_SRC_CODE_SCENE_SPECULAR},
				{zonetool::h1::TEXTURE_SRC_CODE_SCENE_ALBEDO, zonetool::iw7::TEXTURE_SRC_CODE_SCENE_ALBEDO},
				//{zonetool::h1::TEXTURE_SRC_CODE_GENERIC_FLOAT_DATA, zonetool::iw7::TEXTURE_SRC_CODE_GENERIC_FLOAT_DATA},
				//{zonetool::h1::TEXTURE_SRC_CODE_UI3D, zonetool::iw7::TEXTURE_SRC_CODE_UI3D},
				//{zonetool::h1::TEXTURE_SRC_CODE_STREAMING_LOADING, zonetool::iw7::TEXTURE_SRC_CODE_STREAMING_LOADING},
				//{zonetool::h1::TEXTURE_SRC_CODE_MDAO_HDIR, zonetool::iw7::TEXTURE_SRC_CODE_MDAO_HDIR},
				//{zonetool::h1::TEXTURE_SRC_CODE_MDAO_DEPTH, zonetool::iw7::TEXTURE_SRC_CODE_MDAO_DEPTH},
				//{zonetool::h1::TEXTURE_SRC_CODE_MDAO_OCCLUSION_VOLUME, zonetool::iw7::TEXTURE_SRC_CODE_MDAO_OCCLUSION_VOLUME},
				//{zonetool::h1::TEXTURE_SRC_CODE_MDAO_LOOKUP, zonetool::iw7::TEXTURE_SRC_CODE_MDAO_LOOKUP},
				{zonetool::h1::TEXTURE_SRC_CODE_TEXTURE_0, zonetool::iw7::TEXTURE_SRC_CODE_TEXTURE_0},
				{zonetool::h1::TEXTURE_SRC_CODE_COMPOSITE_RESULT, zonetool::iw7::TEXTURE_SRC_CODE_COMPOSITE_RESULT},
				{zonetool::h1::TEXTURE_SRC_CODE_FONT_CACHE, zonetool::iw7::TEXTURE_SRC_CODE_FONT_CACHE},
				{zonetool::h1::TEXTURE_SRC_CODE_COUNT, zonetool::iw7::TEXTURE_SRC_CODE_COUNT},
			};

			std::unordered_map <std::int32_t, std::int32_t> technique_index_map =
			{
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_ZPREPASS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_DEPTH_PREPASS},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_ZPREPASS_VELOCITY_RIGID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_DEPTH_PREPASS_VELOCITY_RIGID},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_ZPREPASS_VELOCITY_SKINNED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_DEPTH_PREPASS_VELOCITY_SKINNED},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_ZPREPASS_HIDIR, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_ZPREPASS_HIDIR},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_ZPREPASS_HIDIR_VELOCITY_RIGID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_ZPREPASS_HIDIR_VELOCITY_RIGID},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_ZPREPASS_HIDIR_VELOCITY_SKINNED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_ZPREPASS_HIDIR_VELOCITY_SKINNED},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_BUILD_SHADOWMAP_DEPTH, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_BUILD_SHADOWMAP_DEPTH},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_BUILD_SHADOWMAP_COLOR, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_BUILD_SHADOWMAP_COLOR},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_UNLIT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_UNLIT},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_EMISSIVE, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_EMISSIVE},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_EMISSIVE_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_EMISSIVE_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_EMISSIVE_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_EMISSIVE_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_EMISSIVE_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_EMISSIVE_SHADOW_DFOG},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_DIR, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_DIR},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_DIR_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_DIR_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_SPOT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_SPOT},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_SPOT_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_SPOT_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_SPOT_SHADOW_CUCOLORIS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_SPOT_SHADOW_CUCOLORIS},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_OMNI, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_OMNI},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_OMNI_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_OMNI_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_DYNAMIC_BRANCHING_CUCOLORIS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_DYNAMIC_BRANCHING_CUCOLORIS},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_DYNAMIC_BRANCHING, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_DYNAMIC_BRANCHING},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_SUN_DYNAMIC_BRANCHING, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_SUN_DYNAMIC_BRANCHING},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_DIR_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_DIR_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_DIR_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_DIR_SHADOW_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_SPOT_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_SPOT_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_SPOT_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_SPOT_SHADOW_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_SPOT_SHADOW_CUCOLORIS_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_SPOT_SHADOW_CUCOLORIS_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_OMNI_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_OMNI_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIT_OMNI_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIT_OMNI_SHADOW_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIGHT_SPOT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIGHT_SPOT},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIGHT_OMNI, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIGHT_OMNI},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_LIGHT_SPOT_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_LIGHT_SPOT_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_FAKELIGHT_NORMAL, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_FAKELIGHT_NORMAL},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_FAKELIGHT_VIEW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_FAKELIGHT_VIEW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_WIREFRAME_SOLID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_WIREFRAME_SOLID},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_WIREFRAME_SHADED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_WIREFRAME_SHADED},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_THERMAL, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_THERMAL},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_VELOCITY_RIGID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_VELOCITY_RIGID},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_VELOCITY_SKINNED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_VELOCITY_SKINNED},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_DEBUG_BUMPMAP, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_DEBUG_BUMPMAP},

				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_ZPREPASS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_DEPTH_PREPASS},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_ZPREPASS_VELOCITY_RIGID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_DEPTH_PREPASS_VELOCITY_RIGID},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_ZPREPASS_VELOCITY_SKINNED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_DEPTH_PREPASS_VELOCITY_SKINNED},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_ZPREPASS_HIDIR, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_ZPREPASS_HIDIR},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_ZPREPASS_HIDIR_VELOCITY_RIGID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_ZPREPASS_HIDIR_VELOCITY_RIGID},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_ZPREPASS_HIDIR_VELOCITY_SKINNED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_ZPREPASS_HIDIR_VELOCITY_SKINNED},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_BUILD_SHADOWMAP_DEPTH, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_BUILD_SHADOWMAP_DEPTH},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_BUILD_SHADOWMAP_COLOR, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_BUILD_SHADOWMAP_COLOR},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_UNLIT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_UNLIT},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_EMISSIVE, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_EMISSIVE},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_EMISSIVE_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_EMISSIVE_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_EMISSIVE_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_EMISSIVE_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_EMISSIVE_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_EMISSIVE_SHADOW_DFOG},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DIR, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DIR},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DIR_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DIR_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SPOT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SPOT},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SPOT_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SPOT_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SPOT_SHADOW_CUCOLORIS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SPOT_SHADOW_CUCOLORIS},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_OMNI, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_OMNI},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_OMNI_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_OMNI_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DYNAMIC_BRANCHING_CUCOLORIS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DYNAMIC_BRANCHING_CUCOLORIS},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DYNAMIC_BRANCHING, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DYNAMIC_BRANCHING},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SUN_DYNAMIC_BRANCHING, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SUN_DYNAMIC_BRANCHING},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DIR_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DIR_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DIR_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_DIR_SHADOW_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SPOT_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SPOT_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SPOT_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SPOT_SHADOW_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SPOT_SHADOW_CUCOLORIS_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_SPOT_SHADOW_CUCOLORIS_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_OMNI_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_OMNI_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_OMNI_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIT_OMNI_SHADOW_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIGHT_SPOT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIGHT_SPOT},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIGHT_OMNI, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIGHT_OMNI},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIGHT_SPOT_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_LIGHT_SPOT_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_FAKELIGHT_NORMAL, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_FAKELIGHT_NORMAL},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_FAKELIGHT_VIEW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_FAKELIGHT_VIEW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_WIREFRAME_SOLID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_WIREFRAME_SOLID},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_WIREFRAME_SHADED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_WIREFRAME_SHADED},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_THERMAL, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_THERMAL},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_VELOCITY_RIGID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_VELOCITY_RIGID},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_VELOCITY_SKINNED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_VELOCITY_SKINNED},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_INSTANCED_DEBUG_BUMPMAP, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_INSTANCED_DEBUG_BUMPMAP},

				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_ZPREPASS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_DEPTH_PREPASS},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_ZPREPASS_VELOCITY_RIGID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_DEPTH_PREPASS_VELOCITY_RIGID},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_ZPREPASS_VELOCITY_SKINNED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_DEPTH_PREPASS_VELOCITY_SKINNED},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_ZPREPASS_HIDIR, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_ZPREPASS_HIDIR},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_ZPREPASS_HIDIR_VELOCITY_RIGID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_ZPREPASS_HIDIR_VELOCITY_RIGID},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_ZPREPASS_HIDIR_VELOCITY_SKINNED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_ZPREPASS_HIDIR_VELOCITY_SKINNED},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_BUILD_SHADOWMAP_DEPTH, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_BUILD_SHADOWMAP_DEPTH},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_BUILD_SHADOWMAP_COLOR, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_BUILD_SHADOWMAP_COLOR},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_UNLIT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_UNLIT},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_EMISSIVE, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_EMISSIVE},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_EMISSIVE_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_EMISSIVE_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_EMISSIVE_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_EMISSIVE_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_EMISSIVE_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_EMISSIVE_SHADOW_DFOG},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DIR, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DIR},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DIR_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DIR_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SPOT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SPOT},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_SHADOW_CUCOLORIS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_SHADOW_CUCOLORIS},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_OMNI, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_OMNI},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_OMNI_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_OMNI_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DYNAMIC_BRANCHING_CUCOLORIS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DYNAMIC_BRANCHING_CUCOLORIS},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DYNAMIC_BRANCHING, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DYNAMIC_BRANCHING},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SUN_DYNAMIC_BRANCHING, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SUN_DYNAMIC_BRANCHING},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DIR_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DIR_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DIR_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_DIR_SHADOW_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_SHADOW_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_SHADOW_CUCOLORIS_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_SPOT_SHADOW_CUCOLORIS_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_OMNI_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_OMNI_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_OMNI_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIT_OMNI_SHADOW_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIGHT_SPOT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIGHT_SPOT},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIGHT_OMNI, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIGHT_OMNI},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIGHT_SPOT_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_LIGHT_SPOT_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_FAKELIGHT_NORMAL, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_FAKELIGHT_NORMAL},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_FAKELIGHT_VIEW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_FAKELIGHT_VIEW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_WIREFRAME_SOLID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_WIREFRAME_SOLID},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_WIREFRAME_SHADED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_WIREFRAME_SHADED},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_THERMAL, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_THERMAL},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_VELOCITY_RIGID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_VELOCITY_RIGID},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_VELOCITY_SKINNED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_VELOCITY_SKINNED},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_DEBUG_BUMPMAP, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_SUBDIV_PATCH_DEBUG_BUMPMAP},

				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_ZPREPASS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_DEPTH_PREPASS},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_VELOCITY_RIGID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_DEPTH_PREPASS_VELOCITY_RIGID},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_VELOCITY_SKINNED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_DEPTH_PREPASS_VELOCITY_SKINNED},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_HIDIR, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_HIDIR},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_HIDIR_VELOCITY_RIGID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_HIDIR_VELOCITY_RIGID},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_HIDIR_VELOCITY_SKINNED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_ZPREPASS_HIDIR_VELOCITY_SKINNED},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_BUILD_SHADOWMAP_DEPTH, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_BUILD_SHADOWMAP_DEPTH},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_BUILD_SHADOWMAP_COLOR, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_BUILD_SHADOWMAP_COLOR},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_UNLIT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_UNLIT},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_EMISSIVE, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_EMISSIVE},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_EMISSIVE_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_EMISSIVE_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_EMISSIVE_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_EMISSIVE_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_EMISSIVE_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_EMISSIVE_SHADOW_DFOG},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DIR, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DIR},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DIR_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DIR_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_SHADOW_CUCOLORIS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_SHADOW_CUCOLORIS},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_OMNI, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_OMNI},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_OMNI_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_OMNI_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DYNAMIC_BRANCHING_CUCOLORIS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DYNAMIC_BRANCHING_CUCOLORIS},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SUN_DYNAMIC_BRANCHING_CUCOLORIS},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DYNAMIC_BRANCHING, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DYNAMIC_BRANCHING},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SUN_DYNAMIC_BRANCHING, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SUN_DYNAMIC_BRANCHING},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DIR_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DIR_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DIR_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_DIR_SHADOW_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_SHADOW_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_SHADOW_CUCOLORIS_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_SPOT_SHADOW_CUCOLORIS_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_OMNI_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_OMNI_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_OMNI_SHADOW_DFOG, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIT_OMNI_SHADOW_DFOG},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIGHT_SPOT, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIGHT_SPOT},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIGHT_OMNI, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIGHT_OMNI},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIGHT_SPOT_SHADOW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_LIGHT_SPOT_SHADOW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_FAKELIGHT_NORMAL, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_FAKELIGHT_NORMAL},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_FAKELIGHT_VIEW, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_FAKELIGHT_VIEW},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_WIREFRAME_SOLID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_WIREFRAME_SOLID},
				//{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_WIREFRAME_SHADED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_WIREFRAME_SHADED},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_THERMAL, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_THERMAL},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_VELOCITY_RIGID, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_VELOCITY_RIGID},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_VELOCITY_SKINNED, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_VELOCITY_SKINNED},
				{zonetool::h1::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_DEBUG_BUMPMAP, zonetool::iw7::MaterialTechniqueType::TECHNIQUE_NO_DISPLACEMENT_DEBUG_BUMPMAP},
			};

			unsigned short convert_code_const(unsigned short index)
			{
				const auto iter = mapped_code_consts.find(index);
				if (iter == mapped_code_consts.end())
				{
					ZONETOOL_ERROR("Couldn't map code const %i", index);
					return zonetool::iw7::CONST_SRC_NONE;
				}
			
				return iter->second;
			}

			unsigned int convert_texture_code(unsigned int index)
			{
				const auto iter = texture_src_code_map.find(index);
				if (iter == texture_src_code_map.end())
				{
					ZONETOOL_ERROR("Couldn't map texture code %i", index);
					return zonetool::iw7::TEXTURE_SRC_CODE_BLACK;
				}

				return iter->second;
			}

			zonetool::iw7::MaterialShaderArgument* convert_shader_arguments(zonetool::h1::MaterialPass* pass, utils::memory::allocator& allocator)
			{
				const auto arg_count = pass->perPrimArgCount + pass->perObjArgCount + pass->stableArgCount;
				const auto converted_args = allocator.allocate_array<zonetool::iw7::MaterialShaderArgument>(arg_count);
				std::memcpy(converted_args, pass->args, sizeof(zonetool::h1::MaterialShaderArgument) * arg_count);

				for (auto i = 0; i < arg_count; i++)
				{
					if (converted_args[i].type == MTL_ARG_CODE_CONST)
					{
						converted_args[i].u.codeConst.index = convert_code_const(converted_args[i].u.codeConst.index);
					}
					else if (converted_args[i].type == MTL_ARG_CODE_TEXTURE || converted_args[i].type == MTL_ARG_CODE_SAMPLER)
					{
						converted_args[i].u.codeSampler = convert_texture_code(converted_args[i].u.codeSampler);
					}
				}

				return converted_args;
			}

			template <typename T, typename S>
			T* convert_shader(S* source, utils::memory::allocator& allocator)
			{
				const auto new_shader = allocator.allocate<T>();
				std::memcpy(reinterpret_cast<char*>(new_shader) + 16, reinterpret_cast<char*>(source) + 8, sizeof(S) - 8);
				new_shader->name = allocator.duplicate_string(game::add_source_postfix(source->name, game::h1));
				return new_shader;
			}

			template <typename T, typename S>
			void convert_shader(T** target, S* source, utils::memory::allocator& allocator)
			{
				if (source == nullptr)
				{
					return;
				}

				*target = convert_shader<T>(source, allocator);
			}

			zonetool::iw7::MaterialTechnique* convert_tech(std::unordered_map<MaterialTechnique*, zonetool::iw7::MaterialTechnique*>& converted_asset_techniques, MaterialTechniqueSet* asset,
				zonetool::iw7::MaterialTechniqueSet* new_asset, utils::memory::allocator& allocator, const std::int32_t tech_index, const std::int32_t new_tech_index)
			{
				const auto technique = asset->techniques[tech_index];
				if (technique == nullptr)
				{
					return nullptr;
				}

				if (const auto iter = converted_asset_techniques.find(technique); iter != converted_asset_techniques.end())
				{
					new_asset->techniques[new_tech_index] = iter->second;
					return iter->second;
				}

				const auto size = sizeof(zonetool::iw7::MaterialTechniqueHeader) + 
					sizeof(zonetool::iw7::MaterialPass) * technique->hdr.passCount;
				const auto new_technique = reinterpret_cast<zonetool::iw7::MaterialTechnique*>(allocator.allocate_array<char>(size));
				std::memcpy(new_technique, technique, size);

				new_technique->hdr.name = allocator.duplicate_string(game::add_source_postfix(technique->hdr.name, game::h1));
				new_technique->hdr.flags = technique->hdr.flags;
				new_technique->hdr.passCount = technique->hdr.passCount;

				for (auto i = 0u; i < technique->hdr.passCount; i++)
				{
					const auto new_pass = &new_technique->passArray[i];
					const auto pass = &technique->passArray[i];

					std::memcpy(new_pass, pass, sizeof(zonetool::h1::MaterialPass));
					std::memset(new_pass->__pad0, 0, sizeof(new_pass->__pad0));

					convert_shader(&new_pass->vertexShader, pass->vertexShader, allocator);
					convert_shader(&new_pass->vertexDecl, pass->vertexDecl, allocator);
					convert_shader(&new_pass->hullShader, pass->hullShader, allocator);
					convert_shader(&new_pass->domainShader, pass->domainShader, allocator);
					convert_shader(&new_pass->pixelShader, pass->pixelShader, allocator);

					new_pass->args = convert_shader_arguments(pass, allocator);
				}

				converted_asset_techniques[technique] = new_technique;
				new_asset->techniques[new_tech_index] = new_technique;

				return new_technique;
			}

			zonetool::iw7::MaterialTechniqueSet* convert(zonetool::h1::MaterialTechniqueSet* asset, utils::memory::allocator& allocator)
			{
				const auto new_asset = allocator.allocate<zonetool::iw7::MaterialTechniqueSet>();

				new_asset->name = allocator.duplicate_string(game::add_source_postfix(asset->name, game::h1));
				COPY_VALUE(flags);
				COPY_VALUE(worldVertFormat);
				COPY_VALUE(preDisplacementOnlyCount);

				new_asset->techniqueCount = zonetool::h1::MaterialTechniqueType::TECHNIQUE_COUNT;
				new_asset->techniques = allocator.allocate_array<zonetool::iw7::MaterialTechnique*>(new_asset->techniqueCount);

				unsigned short technique_index = 0;

				std::unordered_map<MaterialTechnique*, zonetool::iw7::MaterialTechnique*> converted_asset_techniques;

				for (auto i = 0u; i < MaterialTechniqueType::TECHNIQUE_COUNT; i++)
				{
					const auto iter = technique_index_map.find(i);
					if (iter == technique_index_map.end())
					{
						continue;
					}

					if (!convert_tech(converted_asset_techniques, asset, new_asset, allocator, i, technique_index))
					{
						continue;
					}
					technique_index++;

					auto technique_mask_index = iter->second >> 6;
					auto technique_mask_bit = 1ull << (iter->second & zonetool::iw7::TECHNIQUE_MASK);
					new_asset->techniqueMask[technique_mask_index] |= technique_mask_bit;
				}

				new_asset->techniqueCount = technique_index;

				return new_asset;
			}

			void dump(zonetool::h1::ComputeShader* asset)
			{
				utils::memory::allocator allocator;
				const auto converted_shader = convert_shader<zonetool::iw7::ComputeShader>(asset, allocator);
				zonetool::iw7::compute_shader::dump(converted_shader);
			}

			void dump(zonetool::h1::MaterialVertexShader* asset)
			{
				utils::memory::allocator allocator;
				const auto converted_shader = convert_shader<zonetool::iw7::MaterialVertexShader>(asset, allocator);
				zonetool::iw7::vertex_shader::dump(converted_shader);
			}

			void dump(zonetool::h1::MaterialHullShader* asset)
			{
				utils::memory::allocator allocator;
				const auto converted_shader = convert_shader<zonetool::iw7::MaterialHullShader>(asset, allocator);
				zonetool::iw7::hull_shader::dump(converted_shader);
			}

			void dump(zonetool::h1::MaterialDomainShader* asset)
			{
				utils::memory::allocator allocator;
				const auto converted_shader = convert_shader<zonetool::iw7::MaterialDomainShader>(asset, allocator);
				zonetool::iw7::domain_shader::dump(converted_shader);
			}

			void dump(zonetool::h1::MaterialPixelShader* asset)
			{
				utils::memory::allocator allocator;
				const auto converted_shader = convert_shader<zonetool::iw7::MaterialPixelShader>(asset, allocator);
				zonetool::iw7::pixel_shader::dump(converted_shader);
			}

			void dump(zonetool::h1::MaterialTechniqueSet* asset)
			{
				utils::memory::allocator allocator;
				const auto converted_asset = convert(asset, allocator);
				zonetool::iw7::techset::dump(converted_asset);
			}
		}
	}
}
#endif