#include <std_include.hpp>

#include "zonetool/h2/converter/h1/include.hpp"
#include "techset.hpp"
#include "zonetool/h1/assets/techset.hpp"
#include "zonetool/h1/assets/computeshader.hpp"
#include "zonetool/h1/assets/vertexshader.hpp"
#include "zonetool/h1/assets/vertexdecl.hpp"
#include "zonetool/h1/assets/hullshader.hpp"
#include "zonetool/h1/assets/domainshader.hpp"
#include "zonetool/h1/assets/pixelshader.hpp"

#include "zonetool/utils/shader.hpp"

#include <utils/io.hpp>

namespace zonetool::h2
{
	namespace converter::h1
	{
		namespace techset
		{
			std::unordered_map<unsigned short, unsigned short> mapped_code_consts =
			{
				{zonetool::h2::CONST_SRC_CODE_LIGHT_POSITION, zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_DIFFUSE, zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_PHYSICALSIZE, zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FADEOFFSET, zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPECULAR, zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTDIR, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTFACTORS, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT, zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM, zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_POSITION1, zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_DIFFUSE1, zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_PHYSICALSIZE1, zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FADEOFFSET1, zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPECULAR1, zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTDIR1, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTFACTORS1, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT1, zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM1, zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_POSITION2, zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_DIFFUSE2, zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_PHYSICALSIZE2, zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FADEOFFSET2, zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPECULAR2, zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTDIR2, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTFACTORS2, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT2, zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM2, zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_POSITION3, zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_DIFFUSE3, zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_PHYSICALSIZE3, zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FADEOFFSET3, zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPECULAR3, zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTDIR3, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTFACTORS3, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT3, zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM3, zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_0, zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_1, zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_2, zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_3, zonetool::h1::CONST_SRC_CODE_LIGHT_POSITION_DB_ARRAY_3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_0, zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_1, zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_2, zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_3, zonetool::h1::CONST_SRC_CODE_LIGHT_DIFFUSE_DB_ARRAY_3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_0, zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_1, zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_2, zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_3, zonetool::h1::CONST_SRC_CODE_LIGHT_PHYSICALSIZE_DB_ARRAY_3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_0, zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_1, zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_2, zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_3, zonetool::h1::CONST_SRC_CODE_LIGHT_FADEOFFSET_DB_ARRAY_3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_0, zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_1, zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_2, zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_3, zonetool::h1::CONST_SRC_CODE_LIGHT_SPECULAR_DB_ARRAY_3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_0, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_1, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_2, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_3, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTDIR_DB_ARRAY_3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_0, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_1, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_2, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_3, zonetool::h1::CONST_SRC_CODE_LIGHT_SPOTFACTORS_DB_ARRAY_3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_0, zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_1, zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_2, zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_3, zonetool::h1::CONST_SRC_CODE_LIGHT_CUCOLORIS_ANIM_DB_ARRAY_3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_0, zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_1, zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_2, zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_2},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_3, zonetool::h1::CONST_SRC_CODE_LIGHT_FALLOFF_PLACEMENT_DB_ARRAY_3},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_DYN_COUNT, zonetool::h1::CONST_SRC_CODE_LIGHT_DYN_COUNT},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_DYN_TYPES, zonetool::h1::CONST_SRC_CODE_LIGHT_DYN_TYPES},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_DYN_SHADOW_TYPES, zonetool::h1::CONST_SRC_CODE_LIGHT_DYN_SHADOW_TYPES},
				{zonetool::h2::CONST_SRC_CODE_PARTICLE_CLOUD_COLOR, zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_COLOR},
				{zonetool::h2::CONST_SRC_CODE_GAMETIME, zonetool::h1::CONST_SRC_CODE_GAMETIME},
				{zonetool::h2::CONST_SRC_CODE_SYSTEMTIME, zonetool::h1::CONST_SRC_CODE_SYSTEMTIME},
				{zonetool::h2::CONST_SRC_CODE_GENERIC_MATERIAL_DATA, zonetool::h1::CONST_SRC_CODE_GENERIC_MATERIAL_DATA},
				{zonetool::h2::CONST_SRC_CODE_EYEOFFSET, zonetool::h1::CONST_SRC_CODE_EYEOFFSET},
				//{zonetool::h2::CONST_SRC_CODE_RATIO_MASK, zonetool::h1::CONST_SRC_NONE},

				{zonetool::h2::CONST_SRC_CODE_WORLD_MATRIX_EYE_OFFSET, zonetool::h1::CONST_SRC_CODE_WORLD_MATRIX_EYE_OFFSET},
				{zonetool::h2::CONST_SRC_CODE_HUD_OUTLINE_PARMS, zonetool::h1::CONST_SRC_CODE_EMBLEM_LUT_SELECTOR}, // sp CONST_SRC_CODE_HUD_OUTLINE_PARMS mp CONST_SRC_CODE_EMBLEM_LUT_SELECTOR
				{zonetool::h2::CONST_SRC_CODE_MODEL_VELOCITY_PARMS, zonetool::h1::CONST_SRC_CODE_MODEL_VELOCITY_PARMS},
				{zonetool::h2::CONST_SRC_CODE_MODEL_VELOCITY_SKINNED_PARMS, zonetool::h1::CONST_SRC_CODE_MODEL_VELOCITY_SKINNED_PARMS},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROL0, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL0},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROL1, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL1},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROL2, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL2},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROL3, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL3},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROL4, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL4},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROL5, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL5},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROL6, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL6},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROL7, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL7},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROL8, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL8},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROL9, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROL9},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROLA, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROLA},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROLB, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROLB},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROLC, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROLC},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROLD, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROLD},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROLE, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROLE},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_CONTROLF, zonetool::h1::CONST_SRC_CODE_POSTFX_CONTROLF},
				{zonetool::h2::CONST_SRC_CODE_SCRIPT_PARMS, zonetool::h1::CONST_SRC_CODE_SCRIPT_PARMS},
				{zonetool::h2::CONST_SRC_CODE_EFFECT_MODEL_COLOR, zonetool::h1::CONST_SRC_CODE_EFFECT_MODEL_COLOR},
				{zonetool::h2::CONST_SRC_CODE_EFFECT_MODEL_COLOR_EMISSIVE, zonetool::h1::CONST_SRC_CODE_EFFECT_MODEL_COLOR_EMISSIVE},
				{zonetool::h2::CONST_SRC_CODE_FILTER_TAP_0, zonetool::h1::CONST_SRC_CODE_FILTER_TAP_0},
				{zonetool::h2::CONST_SRC_CODE_FILTER_TAP_1, zonetool::h1::CONST_SRC_CODE_FILTER_TAP_1},
				{zonetool::h2::CONST_SRC_CODE_FILTER_TAP_2, zonetool::h1::CONST_SRC_CODE_FILTER_TAP_2},
				{zonetool::h2::CONST_SRC_CODE_FILTER_TAP_3, zonetool::h1::CONST_SRC_CODE_FILTER_TAP_3},
				{zonetool::h2::CONST_SRC_CODE_FILTER_TAP_4, zonetool::h1::CONST_SRC_CODE_FILTER_TAP_4},
				{zonetool::h2::CONST_SRC_CODE_FILTER_TAP_5, zonetool::h1::CONST_SRC_CODE_FILTER_TAP_5},
				{zonetool::h2::CONST_SRC_CODE_FILTER_TAP_6, zonetool::h1::CONST_SRC_CODE_FILTER_TAP_6},
				{zonetool::h2::CONST_SRC_CODE_FILTER_TAP_7, zonetool::h1::CONST_SRC_CODE_FILTER_TAP_7},
				{zonetool::h2::CONST_SRC_CODE_FILTER_TAP_8, zonetool::h1::CONST_SRC_CODE_FILTER_TAP_8},
				{zonetool::h2::CONST_SRC_CODE_FILTER_TAP_9, zonetool::h1::CONST_SRC_CODE_FILTER_TAP_9},
				{zonetool::h2::CONST_SRC_CODE_FILTER_TAP_10, zonetool::h1::CONST_SRC_CODE_FILTER_TAP_10},
				{zonetool::h2::CONST_SRC_CODE_FILTER_TAP_11, zonetool::h1::CONST_SRC_CODE_FILTER_TAP_11},
				{zonetool::h2::CONST_SRC_CODE_COLOR_MATRIX_R, zonetool::h1::CONST_SRC_CODE_COLOR_MATRIX_R},
				{zonetool::h2::CONST_SRC_CODE_COLOR_MATRIX_G, zonetool::h1::CONST_SRC_CODE_COLOR_MATRIX_G},
				{zonetool::h2::CONST_SRC_CODE_COLOR_MATRIX_B, zonetool::h1::CONST_SRC_CODE_COLOR_MATRIX_B},
				{zonetool::h2::CONST_SRC_CODE_RENDER_TARGET_SIZE, zonetool::h1::CONST_SRC_CODE_RENDER_TARGET_SIZE},
				{zonetool::h2::CONST_SRC_CODE_RENDER_SOURCE_SIZE, zonetool::h1::CONST_SRC_CODE_RENDER_SOURCE_SIZE},
				{zonetool::h2::CONST_SRC_CODE_VEIL_PARAMS, zonetool::h1::CONST_SRC_CODE_VEIL_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_FXAA_RCPFRAMEOPT, zonetool::h1::CONST_SRC_CODE_FXAA_RCPFRAMEOPT},
				{zonetool::h2::CONST_SRC_CODE_VOLUME_LIGHT_SCATTER_1, zonetool::h1::CONST_SRC_CODE_VOLUME_LIGHT_SCATTER_1},
				{zonetool::h2::CONST_SRC_CODE_VOLUME_LIGHT_SCATTER_2, zonetool::h1::CONST_SRC_CODE_VOLUME_LIGHT_SCATTER_2},
				{zonetool::h2::CONST_SRC_CODE_VOLUME_LIGHT_SCATTER_3, zonetool::h1::CONST_SRC_CODE_VOLUME_LIGHT_SCATTER_3},
				{zonetool::h2::CONST_SRC_CODE_MODEL_LIGHTMAP_PARAMS, zonetool::h1::CONST_SRC_CODE_MODEL_LIGHTMAP_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_NEARPLANE_ORG, zonetool::h1::CONST_SRC_CODE_NEARPLANE_ORG},
				{zonetool::h2::CONST_SRC_CODE_NEARPLANE_DX, zonetool::h1::CONST_SRC_CODE_NEARPLANE_DX},
				{zonetool::h2::CONST_SRC_CODE_NEARPLANE_DY, zonetool::h1::CONST_SRC_CODE_NEARPLANE_DY},
				{zonetool::h2::CONST_SRC_CODE_SSAO_POWER_BB_SHARPNESS_STEP, zonetool::h1::CONST_SRC_CODE_SSAO_POWER_BB_SHARPNESS_STEP},
				{zonetool::h2::CONST_SRC_CODE_SSAO_COLOR_COEFF, zonetool::h1::CONST_SRC_CODE_SSAO_COLOR_COEFF},
				{zonetool::h2::CONST_SRC_CODE_SSAO_FALLOFF_DEPTH_SCALE, zonetool::h1::CONST_SRC_CODE_SSAO_FALLOFF_DEPTH_SCALE},
				{zonetool::h2::CONST_SRC_CODE_SSAO_UV_TO_ROT_SCALE_AND_FADE, zonetool::h1::CONST_SRC_CODE_SSAO_UV_TO_ROT_SCALE_AND_FADE},
				{zonetool::h2::CONST_SRC_CODE_SSAO_SAMPLE_MAT_SCALE, zonetool::h1::CONST_SRC_CODE_SSAO_SAMPLE_MAT_SCALE},
				{zonetool::h2::CONST_SRC_CODE_SSAO_DEPTH_OFFSET_REJECT, zonetool::h1::CONST_SRC_CODE_SSAO_DEPTH_OFFSET_REJECT},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_LIGHTDIRX2, zonetool::h1::CONST_SRC_CODE_LIT2D_LIGHTDIRX2},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_SPECHALFANGLEDIRX2, zonetool::h1::CONST_SRC_CODE_LIT2D_SPECHALFANGLEDIRX2},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_AMBIENTCOLOR, zonetool::h1::CONST_SRC_CODE_LIT2D_AMBIENTCOLOR},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_DIFFUSECOLOR, zonetool::h1::CONST_SRC_CODE_LIT2D_DIFFUSECOLOR},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_SPECCOLOR_SPECEXPONENT, zonetool::h1::CONST_SRC_CODE_LIT2D_SPECCOLOR_SPECEXPONENT},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_ADDITIVECOLOR, zonetool::h1::CONST_SRC_CODE_LIT2D_ADDITIVECOLOR},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_BLOODSPATTER_AMBIENTCOLOR, zonetool::h1::CONST_SRC_CODE_LIT2D_BLOODSPATTER_AMBIENTCOLOR},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_BLOODSPATTER_DIFFUSECOLOR, zonetool::h1::CONST_SRC_CODE_LIT2D_BLOODSPATTER_DIFFUSECOLOR},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_BLOODSPATTER_SPECCOLOR_SPECEXPONENT, zonetool::h1::CONST_SRC_CODE_LIT2D_BLOODSPATTER_SPECCOLOR_SPECEXPONENT},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_BLOODSPATTER_ADDITIVECOLOR, zonetool::h1::CONST_SRC_CODE_LIT2D_BLOODSPATTER_ADDITIVECOLOR},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_HUDBLOOD_COLOR, zonetool::h1::CONST_SRC_CODE_LIT2D_HUDBLOOD_COLOR},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_HUDBLOOD_COLOR_THIN, zonetool::h1::CONST_SRC_CODE_LIT2D_HUDBLOOD_COLOR_THIN},
				{zonetool::h2::CONST_SRC_CODE_DOF_EQUATION_VIEWMODEL_AND_FAR_BLUR, zonetool::h1::CONST_SRC_CODE_DOF_EQUATION_VIEWMODEL_AND_FAR_BLUR},
				{zonetool::h2::CONST_SRC_CODE_DOF_EQUATION_SCENE, zonetool::h1::CONST_SRC_CODE_DOF_EQUATION_SCENE},
				{zonetool::h2::CONST_SRC_CODE_DOF_UNK, zonetool::h1::CONST_SRC_CODE_DOF_EQUATION_SCENE},

				{zonetool::h2::CONST_SRC_CODE_DOF_LERP_SCALE, zonetool::h1::CONST_SRC_CODE_DOF_LERP_SCALE},
				{zonetool::h2::CONST_SRC_CODE_DOF_LERP_BIAS, zonetool::h1::CONST_SRC_CODE_DOF_LERP_BIAS},
				{zonetool::h2::CONST_SRC_CODE_DOF_ROW_DELTA, zonetool::h1::CONST_SRC_CODE_DOF_ROW_DELTA},
				{zonetool::h2::CONST_SRC_CODE_DOF_EQUATION, zonetool::h1::CONST_SRC_CODE_DOF_EQUATION},
				{zonetool::h2::CONST_SRC_CODE_DOF_PARAMS, zonetool::h1::CONST_SRC_CODE_DOF_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_DOF_TILE_PARAMS, zonetool::h1::CONST_SRC_CODE_DOF_TILE_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_FRAME_COUNT_PARAMS, zonetool::h1::CONST_SRC_CODE_FRAME_COUNT_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_MOTION_MATRIX_X, zonetool::h1::CONST_SRC_CODE_MOTION_MATRIX_X},
				{zonetool::h2::CONST_SRC_CODE_MOTION_MATRIX_Y, zonetool::h1::CONST_SRC_CODE_MOTION_MATRIX_Y},
				{zonetool::h2::CONST_SRC_CODE_MOTION_MATRIX_W, zonetool::h1::CONST_SRC_CODE_MOTION_MATRIX_W},
				{zonetool::h2::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R0, zonetool::h1::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R0},
				{zonetool::h2::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R1, zonetool::h1::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R1},
				{zonetool::h2::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R2, zonetool::h1::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R2},
				{zonetool::h2::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R3, zonetool::h1::CONST_SRC_CODE_SSR_PREV_FRAME_VIEWPROJECTION_MATRIX_R3},
				{zonetool::h2::CONST_SRC_CODE_PREV_EYEPOSITION_TRANSFORM, zonetool::h1::CONST_SRC_CODE_PREV_EYEPOSITION_TRANSFORM},
				{zonetool::h2::CONST_SRC_CODE_SCREEN_SPACE_REFLECTION_PARAMETERS, zonetool::h1::CONST_SRC_CODE_SCREEN_SPACE_REFLECTION_PARAMETERS},
				{zonetool::h2::CONST_SRC_CODE_CLIP_SPACE_LOOKUP_SCALE_AND_OFFSET, zonetool::h1::CONST_SRC_CODE_CLIP_SPACE_LOOKUP_SCALE_AND_OFFSET},
				{zonetool::h2::CONST_SRC_CODE_SSR_CLIP_TO_FADE_SCALE_OFFSET_PS, zonetool::h1::CONST_SRC_CODE_SSR_CLIP_TO_FADE_SCALE_OFFSET_PS},
				{zonetool::h2::CONST_SRC_CODE_SSS_MRT_OFF_SHADER_OFF, zonetool::h1::CONST_SRC_CODE_SSS_MRT_OFF_SHADER_OFF},
				{zonetool::h2::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R0, zonetool::h1::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R0},
				{zonetool::h2::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R1, zonetool::h1::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R1},
				{zonetool::h2::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R2, zonetool::h1::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R2},
				{zonetool::h2::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R3, zonetool::h1::CONST_SRC_CODE_MDAO_VIEWTOOCCLUDER_MATRIX_R3},
				{zonetool::h2::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R0, zonetool::h1::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R0},
				{zonetool::h2::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R1, zonetool::h1::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R1},
				{zonetool::h2::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R2, zonetool::h1::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R2},
				{zonetool::h2::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R3, zonetool::h1::CONST_SRC_CODE_MDAO_WORLDTOOCCLUDERFRAME_MATRIX_R3},
				{zonetool::h2::CONST_SRC_CODE_MDAO_SCREEN_PARAMS, zonetool::h1::CONST_SRC_CODE_MDAO_SCREEN_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_MDAO_CAMERA_PARAMS, zonetool::h1::CONST_SRC_CODE_MDAO_CAMERA_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_MDAO_LOOKUP_PARAMS, zonetool::h1::CONST_SRC_CODE_MDAO_LOOKUP_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_MDAO_VOLUME_PARAMS, zonetool::h1::CONST_SRC_CODE_MDAO_VOLUME_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_DISTORTION_SAMPLE_LIMITS_PS, zonetool::h1::CONST_SRC_CODE_DISTORTION_SAMPLE_LIMITS_PS},
				{zonetool::h2::CONST_SRC_CODE_SCOPE_SAMPLE_LIMITS_PS, zonetool::h1::CONST_SRC_CODE_SCOPE_SAMPLE_LIMITS_PS},
				{zonetool::h2::CONST_SRC_CODE_UV_TO_PREV_SCALED_CLIP_MAT_C0_PS, zonetool::h1::CONST_SRC_CODE_UV_TO_PREV_SCALED_CLIP_MAT_C0_PS},
				{zonetool::h2::CONST_SRC_CODE_UV_TO_PREV_SCALED_CLIP_MAT_C1_PS, zonetool::h1::CONST_SRC_CODE_UV_TO_PREV_SCALED_CLIP_MAT_C1_PS},
				{zonetool::h2::CONST_SRC_CODE_UV_TO_PREV_SCALED_CLIP_MAT_C3_PS, zonetool::h1::CONST_SRC_CODE_UV_TO_PREV_SCALED_CLIP_MAT_C3_PS},
				{zonetool::h2::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R0, zonetool::h1::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R0},
				{zonetool::h2::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R1, zonetool::h1::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R1},
				{zonetool::h2::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R2, zonetool::h1::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R2},
				{zonetool::h2::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R3, zonetool::h1::CONST_SRC_CODE_PREV_FRAME_VIEWPROJECTION_MATRIX_R3},
				{zonetool::h2::CONST_SRC_CODE_PREV_FRAME_WORLD_MATRIX_EYE_OFFSET, zonetool::h1::CONST_SRC_CODE_PREV_FRAME_WORLD_MATRIX_EYE_OFFSET},
				{zonetool::h2::CONST_SRC_CODE_STATIC_VELOCITY_PARMS, zonetool::h1::CONST_SRC_CODE_STATIC_VELOCITY_PARMS},
				{zonetool::h2::CONST_SRC_CODE_MOTION_BLUR_HQ_PARAMS, zonetool::h1::CONST_SRC_CODE_MOTION_BLUR_HQ_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_MOTION_BLUR_HQ_TILE_MAX_PARAMS, zonetool::h1::CONST_SRC_CODE_MOTION_BLUR_HQ_TILE_MAX_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_MB_UV_TO_PREV_SCALED_CLIP_MAT_C0_PS, zonetool::h1::CONST_SRC_CODE_MB_UV_TO_PREV_SCALED_CLIP_MAT_C0_PS},
				{zonetool::h2::CONST_SRC_CODE_MB_UV_TO_PREV_SCALED_CLIP_MAT_C1_PS, zonetool::h1::CONST_SRC_CODE_MB_UV_TO_PREV_SCALED_CLIP_MAT_C1_PS},
				{zonetool::h2::CONST_SRC_CODE_MB_UV_TO_PREV_SCALED_CLIP_MAT_C3_PS, zonetool::h1::CONST_SRC_CODE_MB_UV_TO_PREV_SCALED_CLIP_MAT_C3_PS},
				{zonetool::h2::CONST_SRC_CODE_SHADOWMAP_SWITCH_PARTITION_ARRAY_0, zonetool::h1::CONST_SRC_CODE_SHADOWMAP_SWITCH_PARTITION_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_SHADOWMAP_SWITCH_PARTITION_ARRAY_1, zonetool::h1::CONST_SRC_CODE_SHADOWMAP_SWITCH_PARTITION_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_SHADOWMAP_DISTANCE_BIAS, zonetool::h1::CONST_SRC_CODE_SHADOWMAP_DISTANCE_BIAS},
				{zonetool::h2::CONST_SRC_CODE_SHADOWMAP_SCALE, zonetool::h1::CONST_SRC_CODE_SHADOWMAP_SCALE},
				{zonetool::h2::CONST_SRC_CODE_SHADOWMAP_PARTITION_UV_OFFSET, zonetool::h1::CONST_SRC_CODE_SHADOWMAP_PARTITION_UV_OFFSET},
				{zonetool::h2::CONST_SRC_CODE_SHADOWMAP_CASCADE_MASK, zonetool::h1::CONST_SRC_CODE_SHADOWMAP_CASCADE_MASK},
				{zonetool::h2::CONST_SRC_CODE_SHADOWMAP_DISTANCE_BLEND, zonetool::h1::CONST_SRC_CODE_SHADOWMAP_DISTANCE_BLEND},
				{zonetool::h2::CONST_SRC_CODE_ZNEAR, zonetool::h1::CONST_SRC_CODE_ZNEAR},
				{zonetool::h2::CONST_SRC_CODE_LIGHTING_LOOKUP_SCALE, zonetool::h1::CONST_SRC_CODE_LIGHTING_LOOKUP_SCALE},
				{zonetool::h2::CONST_SRC_CODE_INV_SCENE_PROJECTION, zonetool::h1::CONST_SRC_CODE_INV_SCENE_PROJECTION},
				{zonetool::h2::CONST_SRC_CODE_RIM_LIGHT_0_DIR, zonetool::h1::CONST_SRC_CODE_RIM_LIGHT_0_DIR},
				{zonetool::h2::CONST_SRC_CODE_RIM_LIGHT_0_COLOR, zonetool::h1::CONST_SRC_CODE_RIM_LIGHT_0_COLOR},
				{zonetool::h2::CONST_SRC_CODE_RIM_LIGHT_1_DIR, zonetool::h1::CONST_SRC_CODE_RIM_LIGHT_1_DIR},
				{zonetool::h2::CONST_SRC_CODE_RIM_LIGHT_1_COLOR, zonetool::h1::CONST_SRC_CODE_RIM_LIGHT_1_COLOR},
				{zonetool::h2::CONST_SRC_CODE_RIM_LIGHT_TECHNIQUE, zonetool::h1::CONST_SRC_CODE_RIM_LIGHT_TECHNIQUE},
				{zonetool::h2::CONST_SRC_CODE_DEBUG_BUMPMAP, zonetool::h1::CONST_SRC_CODE_DEBUG_BUMPMAP},
				//{zonetool::h2::CONST_SRC_CODE_DEBUG_TEXDENSITY, zonetool::h1::CONST_SRC_NONE},

				{zonetool::h2::CONST_SRC_CODE_MATERIAL_COLOR, zonetool::h1::CONST_SRC_CODE_MATERIAL_COLOR},
				{zonetool::h2::CONST_SRC_CODE_FOG, zonetool::h1::CONST_SRC_CODE_FOG},
				{zonetool::h2::CONST_SRC_CODE_FOG_COLOR_LINEAR, zonetool::h1::CONST_SRC_CODE_FOG_COLOR_LINEAR},
				{zonetool::h2::CONST_SRC_CODE_FOG_COLOR_GAMMA, zonetool::h1::CONST_SRC_CODE_FOG_COLOR_GAMMA},
				{zonetool::h2::CONST_SRC_CODE_FOG_SUN_CONSTS, zonetool::h1::CONST_SRC_CODE_FOG_SUN_CONSTS},
				{zonetool::h2::CONST_SRC_CODE_FOG_SUN_COLOR_LINEAR, zonetool::h1::CONST_SRC_CODE_FOG_SUN_COLOR_LINEAR},
				{zonetool::h2::CONST_SRC_CODE_FOG_SUN_COLOR_GAMMA, zonetool::h1::CONST_SRC_CODE_FOG_SUN_COLOR_GAMMA},
				{zonetool::h2::CONST_SRC_CODE_FOG_SUN_DIR, zonetool::h1::CONST_SRC_CODE_FOG_SUN_DIR},
				{zonetool::h2::CONST_SRC_CODE_FOG_SKY_FOG, zonetool::h1::CONST_SRC_CODE_FOG_SKY_FOG},
				{zonetool::h2::CONST_SRC_CODE_FOG_HEIGHT_FOG, zonetool::h1::CONST_SRC_CODE_FOG_HEIGHT_FOG},
				{zonetool::h2::CONST_SRC_CODE_ATMOS_FOG_PARMS_0, zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_0},
				{zonetool::h2::CONST_SRC_CODE_ATMOS_FOG_PARMS_1, zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_1},
				{zonetool::h2::CONST_SRC_CODE_ATMOS_FOG_PARMS_2, zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_2},
				{zonetool::h2::CONST_SRC_CODE_ATMOS_FOG_PARMS_3, zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_3},
				{zonetool::h2::CONST_SRC_CODE_ATMOS_FOG_PARMS_4, zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_4},
				{zonetool::h2::CONST_SRC_CODE_ATMOS_FOG_PARMS_5, zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_5},
				{zonetool::h2::CONST_SRC_CODE_ATMOS_FOG_PARMS_6, zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_6},
				//{zonetool::h2::CONST_SRC_CODE_ATMOS_FOG_PARMS_7, zonetool::h1::CONST_SRC_NONE},
				{zonetool::h2::CONST_SRC_CODE_ATMOS_FOG_PARMS_7, zonetool::h1::CONST_SRC_CODE_ATMOS_FOG_PARMS_6},

				{zonetool::h2::CONST_SRC_CODE_FOG_SKY_DIR, zonetool::h1::CONST_SRC_CODE_FOG_SKY_DIR},
				{zonetool::h2::CONST_SRC_CODE_FOG_DEPTHHACK, zonetool::h1::CONST_SRC_CODE_FOG_DEPTHHACK},
				{zonetool::h2::CONST_SRC_CODE_GLOW_SETUP, zonetool::h1::CONST_SRC_CODE_GLOW_SETUP},
				{zonetool::h2::CONST_SRC_CODE_GLOW_APPLY, zonetool::h1::CONST_SRC_CODE_GLOW_APPLY},
				{zonetool::h2::CONST_SRC_CODE_GLOW_SETUP_ALT_COLOR_SCALE, zonetool::h1::CONST_SRC_CODE_GLOW_SETUP_ALT_COLOR_SCALE},
				{zonetool::h2::CONST_SRC_CODE_COLOR_BIAS, zonetool::h1::CONST_SRC_CODE_COLOR_BIAS},
				{zonetool::h2::CONST_SRC_CODE_COLOR_TINT_BASE, zonetool::h1::CONST_SRC_CODE_COLOR_TINT_BASE},
				{zonetool::h2::CONST_SRC_CODE_COLOR_TINT_DELTA, zonetool::h1::CONST_SRC_CODE_COLOR_TINT_DELTA},
				{zonetool::h2::CONST_SRC_CODE_COLOR_TINT_QUADRATIC_DELTA, zonetool::h1::CONST_SRC_CODE_COLOR_TINT_QUADRATIC_DELTA},
				//{zonetool::h2::CONST_SRC_CODE_COLOR_TINT_HDR_CROSSOVER, zonetool::h1::CONST_SRC_NONE},
				//{zonetool::h2::CONST_SRC_CODE_COLOR_TINT_HDR_DARK, zonetool::h1::CONST_SRC_NONE},
				//{zonetool::h2::CONST_SRC_CODE_COLOR_TINT_HDR_DARK_TANGENT, zonetool::h1::CONST_SRC_NONE},
				//{zonetool::h2::CONST_SRC_CODE_COLOR_TINT_HDR_MEDIUM, zonetool::h1::CONST_SRC_NONE},
				//{zonetool::h2::CONST_SRC_CODE_COLOR_TINT_HDR_MEDIUM_TANGENT, zonetool::h1::CONST_SRC_NONE},
				//{zonetool::h2::CONST_SRC_CODE_COLOR_TINT_HDR_LIGHT, zonetool::h1::CONST_SRC_NONE},
				//{zonetool::h2::CONST_SRC_CODE_COLOR_TINT_HDR_LIGHT_TANGENT, zonetool::h1::CONST_SRC_NONE},
				//{zonetool::h2::CONST_SRC_CODE_COLOR_TINT_HDR_SPECULAR, zonetool::h1::CONST_SRC_NONE},
				//{zonetool::h2::CONST_SRC_CODE_COLOR_TINT_HDR_SPECULAR_TANGENT, zonetool::h1::CONST_SRC_NONE},
				{zonetool::h2::CONST_SRC_CODE_PERCEPTUAL_PARMS, zonetool::h1::CONST_SRC_CODE_PERCEPTUAL_PARMS},
				{zonetool::h2::CONST_SRC_CODE_FILMIC_PARMS, zonetool::h1::CONST_SRC_CODE_FILMIC_PARMS},
				{zonetool::h2::CONST_SRC_CODE_FILMIC_SHOULDER_PARMS, zonetool::h1::CONST_SRC_CODE_FILMIC_SHOULDER_PARMS},
				{zonetool::h2::CONST_SRC_CODE_FILMIC_TOE_PARMS, zonetool::h1::CONST_SRC_CODE_FILMIC_TOE_PARMS},
				{zonetool::h2::CONST_SRC_CODE_TONEMAP_PARMS, zonetool::h1::CONST_SRC_CODE_TONEMAP_PARMS},
				{zonetool::h2::CONST_SRC_CODE_HDR_STAGE_PARMS, zonetool::h1::CONST_SRC_CODE_HDR_STAGE_PARMS},
				{zonetool::h2::CONST_SRC_CODE_UI3D_UV_SETUP_0, zonetool::h1::CONST_SRC_CODE_UI3D_UV_SETUP_0},
				{zonetool::h2::CONST_SRC_CODE_UI3D_UV_SETUP_1, zonetool::h1::CONST_SRC_CODE_UI3D_UV_SETUP_1},
				{zonetool::h2::CONST_SRC_CODE_UI3D_UV_SETUP_2, zonetool::h1::CONST_SRC_CODE_UI3D_UV_SETUP_2},
				{zonetool::h2::CONST_SRC_CODE_UI3D_UV_SETUP_3, zonetool::h1::CONST_SRC_CODE_UI3D_UV_SETUP_3},
				{zonetool::h2::CONST_SRC_CODE_UI3D_UV_SETUP_4, zonetool::h1::CONST_SRC_CODE_UI3D_UV_SETUP_4},
				{zonetool::h2::CONST_SRC_CODE_UI3D_UV_SETUP_5, zonetool::h1::CONST_SRC_CODE_UI3D_UV_SETUP_5},
				{zonetool::h2::CONST_SRC_CODE_HUDFX_PARMS, zonetool::h1::CONST_SRC_CODE_HUDFX_PARMS},
				{zonetool::h2::CONST_SRC_CODE_HUDFX_PARMS2, zonetool::h1::CONST_SRC_CODE_HUDFX_PARMS2},
				{zonetool::h2::CONST_SRC_CODE_SSSS_PARAMS, zonetool::h1::CONST_SRC_CODE_SSSS_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_SSSS_SCALE, zonetool::h1::CONST_SRC_CODE_SSSS_SCALE},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_0, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_0},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_1, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_1},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_2, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_2},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_3, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_3},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_4, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_4},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_5, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_5},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_6, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_6},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_7, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_7},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_8, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_8},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_9, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_9},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_10, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_10},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_11, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_11},
				{zonetool::h2::CONST_SRC_CODE_SSSS_KERNEL_12, zonetool::h1::CONST_SRC_CODE_SSSS_KERNEL_12},
				{zonetool::h2::CONST_SRC_CODE_OUTDOOR_FEATHER_PARMS, zonetool::h1::CONST_SRC_CODE_OUTDOOR_FEATHER_PARMS},
				{zonetool::h2::CONST_SRC_CODE_ENVMAP_PARMS, zonetool::h1::CONST_SRC_CODE_ENVMAP_PARMS},
				{zonetool::h2::CONST_SRC_CODE_SUN_SHADOWMAP_PIXEL_ADJUST_ARRAY_0, zonetool::h1::CONST_SRC_CODE_SUN_SHADOWMAP_PIXEL_ADJUST_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_SUN_SHADOWMAP_PIXEL_ADJUST_ARRAY_1, zonetool::h1::CONST_SRC_CODE_SUN_SHADOWMAP_PIXEL_ADJUST_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_SUN_SHADOWMAP_PIXEL_ADJUST_ARRAY_2, zonetool::h1::CONST_SRC_CODE_SUN_SHADOWMAP_PIXEL_ADJUST_ARRAY_2},
				{zonetool::h2::CONST_SRC_CODE_SUN_SHADOWMAP_CASCADE_V_CLAMP, zonetool::h1::CONST_SRC_CODE_SUN_SHADOWMAP_CASCADE_V_CLAMP},
				{zonetool::h2::CONST_SRC_CODE_SUN_SHADOWMAP_NEAR_FAR_PLANE, zonetool::h1::CONST_SRC_CODE_SUN_SHADOWMAP_NEAR_FAR_PLANE},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_1, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_1},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_2, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_2},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_3, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_3},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_0, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_1, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_2, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_2},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_3, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_PIXEL_ADJUST_ARRAY_3},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_1, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_1},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_2, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_2},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_3, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_3},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_0, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_0},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_1, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_1},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_2, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_2},
				{zonetool::h2::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_3, zonetool::h1::CONST_SRC_CODE_SPOT_SHADOWMAP_ZTRANSFORM_ARRAY_3},
				{zonetool::h2::CONST_SRC_CODE_COMPOSITE_FX_DISTORTION, zonetool::h1::CONST_SRC_CODE_COMPOSITE_FX_DISTORTION},
				{zonetool::h2::CONST_SRC_CODE_POSTFX_FADE_EFFECT, zonetool::h1::CONST_SRC_CODE_POSTFX_FADE_EFFECT},
				{zonetool::h2::CONST_SRC_CODE_SCENE_UV_MULT, zonetool::h1::CONST_SRC_CODE_SCENE_UV_MULT},
				{zonetool::h2::CONST_SRC_CODE_SCENE_VIEW_MULT, zonetool::h1::CONST_SRC_CODE_SCENE_VIEW_MULT},
				{zonetool::h2::CONST_SRC_CODE_TEXCOORD_CLAMP_0, zonetool::h1::CONST_SRC_CODE_TEXCOORD_CLAMP_0},
				{zonetool::h2::CONST_SRC_CODE_TEXCOORD_CLAMP_1, zonetool::h1::CONST_SRC_CODE_TEXCOORD_CLAMP_1},
				{zonetool::h2::CONST_SRC_CODE_VIEWPORT_DIMENSIONS, zonetool::h1::CONST_SRC_CODE_VIEWPORT_DIMENSIONS},
				{zonetool::h2::CONST_SRC_CODE_FRAMEBUFFER_READ, zonetool::h1::CONST_SRC_CODE_FRAMEBUFFER_READ},
				{zonetool::h2::CONST_SRC_CODE_THERMAL_COLOR_OFFSET, zonetool::h1::CONST_SRC_CODE_THERMAL_COLOR_OFFSET},
				{zonetool::h2::CONST_SRC_CODE_THERMAL_FADE_CONTROL, zonetool::h1::CONST_SRC_CODE_THERMAL_FADE_CONTROL},
				{zonetool::h2::CONST_SRC_CODE_THERMAL_FADE_COLOR, zonetool::h1::CONST_SRC_CODE_THERMAL_FADE_COLOR},
				{zonetool::h2::CONST_SRC_CODE_PLAYLIST_POPULATION_PARAMS, zonetool::h1::CONST_SRC_CODE_PLAYLIST_POPULATION_PARAMS},
				{zonetool::h2::CONST_SRC_CODE_TESSELLATION_PARMS, zonetool::h1::CONST_SRC_CODE_TESSELLATION_PARMS},
				{zonetool::h2::CONST_SRC_CODE_TESSELLATION_PARMS2, zonetool::h1::CONST_SRC_CODE_TESSELLATION_PARMS2},
				{zonetool::h2::CONST_SRC_CODE_EYE_PARAMETER_DVAR, zonetool::h1::CONST_SRC_CODE_EYE_PARAMETER_DVAR},
				{zonetool::h2::CONST_SRC_CODE_MP_RIM_PARAMETER_DVAR1, zonetool::h1::CONST_SRC_CODE_MP_RIM_PARAMETER_DVAR1},
				{zonetool::h2::CONST_SRC_CODE_MP_RIM_PARAMETER_DVAR2, zonetool::h1::CONST_SRC_CODE_MP_RIM_PARAMETER_DVAR2},
				{zonetool::h2::CONST_SRC_CODE_HEAD_ROT_MAT_R0, zonetool::h1::CONST_SRC_CODE_HEAD_ROT_MAT_R0},
				{zonetool::h2::CONST_SRC_CODE_HEAD_ROT_MAT_R1, zonetool::h1::CONST_SRC_CODE_HEAD_ROT_MAT_R1},
				{zonetool::h2::CONST_SRC_CODE_HEAD_ROT_MAT_R2, zonetool::h1::CONST_SRC_CODE_HEAD_ROT_MAT_R2},
				{zonetool::h2::CONST_SRC_CODE_GUN_SIGHT_COLOR, zonetool::h1::CONST_SRC_CODE_GUN_SIGHT_COLOR},
				{zonetool::h2::CONST_SRC_CODE_GUN_RETICLE_COLOR, zonetool::h1::CONST_SRC_CODE_GUN_RETICLE_COLOR},
				//{zonetool::h2::CONST_SRC_CODE_ADS_OVERLAY_RECT, zonetool::h1::CONST_SRC_NONE},

				{zonetool::h2::CONST_SRC_CODE_BASE_LIGHTING_COORDS, zonetool::h1::CONST_SRC_CODE_BASE_LIGHTING_COORDS},
				{zonetool::h2::CONST_SRC_CODE_LIGHT_PROBE_AMBIENT, zonetool::h1::CONST_SRC_CODE_LIGHT_PROBE_AMBIENT},
				{zonetool::h2::CONST_SRC_CODE_CLIP_SPACE_LOOKUP_SCALE, zonetool::h1::CONST_SRC_CODE_CLIP_SPACE_LOOKUP_SCALE},
				{zonetool::h2::CONST_SRC_CODE_CLIP_SPACE_LOOKUP_OFFSET, zonetool::h1::CONST_SRC_CODE_CLIP_SPACE_LOOKUP_OFFSET},
				{zonetool::h2::CONST_SRC_CODE_PARTICLE_CLOUD_TEXTURE_ATLAS_SETTINGS, zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_TEXTURE_ATLAS_SETTINGS},
				{zonetool::h2::CONST_SRC_CODE_PARTICLE_CLOUD_VEL_WORLD, zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_VEL_WORLD},
				{zonetool::h2::CONST_SRC_CODE_PARTICLE_CLOUD_MATRIX0, zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_PARTICLE_CLOUD_MATRIX1, zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_PARTICLE_CLOUD_MATRIX2, zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_PARTICLE_CLOUD_SPARK_COLOR0, zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_SPARK_COLOR0},
				{zonetool::h2::CONST_SRC_CODE_PARTICLE_CLOUD_SPARK_COLOR1, zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_SPARK_COLOR1},
				{zonetool::h2::CONST_SRC_CODE_PARTICLE_CLOUD_SPARK_COLOR2, zonetool::h1::CONST_SRC_CODE_PARTICLE_CLOUD_SPARK_COLOR2},
				{zonetool::h2::CONST_SRC_CODE_PARTICLE_FOUNTAIN_PARM0, zonetool::h1::CONST_SRC_CODE_PARTICLE_FOUNTAIN_PARM0},
				{zonetool::h2::CONST_SRC_CODE_PARTICLE_FOUNTAIN_PARM1, zonetool::h1::CONST_SRC_CODE_PARTICLE_FOUNTAIN_PARM1},
				{zonetool::h2::CONST_SRC_CODE_LIT2D_BLOODSPATTER_FADESHARPNESS, zonetool::h1::CONST_SRC_CODE_LIT2D_BLOODSPATTER_FADESHARPNESS},
				{zonetool::h2::CONST_SRC_CODE_BLUR_SCENE_PIXEL_POS_TO_UV, zonetool::h1::CONST_SRC_CODE_BLUR_SCENE_PIXEL_POS_TO_UV},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_0, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_0},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_1, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_1},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_2, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_2},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_3, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_3},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_4, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_4},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_5, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_5},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_6, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_6},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_7, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_7},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_8, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_8},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_9, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_9},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_10, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_10},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_11, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_11},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_12, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_12},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_13, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_13},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_14, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_14},
				{zonetool::h2::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_15, zonetool::h1::CONST_SRC_CODE_REACTIVEMOTION_CENTERS_15},
				{zonetool::h2::CONST_SRC_CODE_DEPTH_FROM_CLIP, zonetool::h1::CONST_SRC_CODE_DEPTH_FROM_CLIP},
				{zonetool::h2::CONST_SRC_CODE_CODE_MESH_ARG_0, zonetool::h1::CONST_SRC_CODE_CODE_MESH_ARG_0},
				{zonetool::h2::CONST_SRC_CODE_CODE_MESH_ARG_1, zonetool::h1::CONST_SRC_CODE_CODE_MESH_ARG_1},
				{zonetool::h2::CONST_SRC_CODE_CODE_MESH_ARG_3, zonetool::h1::CONST_SRC_CODE_CODE_MESH_ARG_3},
				{zonetool::h2::CONST_SRC_CODE_CODE_MESH_ARG_4, zonetool::h1::CONST_SRC_CODE_CODE_MESH_ARG_4},
				{zonetool::h2::CONST_SRC_CODE_SCRIPT_CONST0, zonetool::h1::CONST_SRC_CODE_SCRIPT_CONST0},
				{zonetool::h2::CONST_SRC_CODE_VIEW_MATRIX, zonetool::h1::CONST_SRC_CODE_VIEW_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_VIEW_MATRIX, zonetool::h1::CONST_SRC_CODE_INVERSE_VIEW_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_VIEW_MATRIX, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_VIEW_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_VIEW_MATRIX, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_VIEW_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_PROJECTION_MATRIX, zonetool::h1::CONST_SRC_CODE_PROJECTION_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_PROJECTION_MATRIX, zonetool::h1::CONST_SRC_CODE_INVERSE_PROJECTION_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_PROJECTION_MATRIX, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_PROJECTION_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_PROJECTION_MATRIX, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_PROJECTION_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_VIEW_PROJECTION_MATRIX, zonetool::h1::CONST_SRC_CODE_VIEW_PROJECTION_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_VIEW_PROJECTION_MATRIX, zonetool::h1::CONST_SRC_CODE_INVERSE_VIEW_PROJECTION_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_VIEW_PROJECTION_MATRIX, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_VIEW_PROJECTION_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_VIEW_PROJECTION_MATRIX, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_VIEW_PROJECTION_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX, zonetool::h1::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX, zonetool::h1::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX1, zonetool::h1::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX1, zonetool::h1::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX1, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX1, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX2, zonetool::h1::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX2, zonetool::h1::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX2, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX2, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX3, zonetool::h1::CONST_SRC_CODE_SHADOW_LOOKUP_MATRIX3},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX3, zonetool::h1::CONST_SRC_CODE_INVERSE_SHADOW_LOOKUP_MATRIX3},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX3, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_SHADOW_LOOKUP_MATRIX3},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX3, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_SHADOW_LOOKUP_MATRIX3},
				{zonetool::h2::CONST_SRC_CODE_WORLD_OUTDOOR_LOOKUP_MATRIX, zonetool::h1::CONST_SRC_CODE_WORLD_OUTDOOR_LOOKUP_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_WORLD_OUTDOOR_LOOKUP_MATRIX, zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_OUTDOOR_LOOKUP_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_WORLD_OUTDOOR_LOOKUP_MATRIX, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_OUTDOOR_LOOKUP_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_OUTDOOR_LOOKUP_MATRIX, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_OUTDOOR_LOOKUP_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_PREV_FRAME_WORLD_MATRIX, zonetool::h1::CONST_SRC_CODE_PREV_FRAME_WORLD_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_PREV_FRAME_INVERSE_WORLD_MATRIX, zonetool::h1::CONST_SRC_CODE_PREV_FRAME_INVERSE_WORLD_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_PREV_FRAME_TRANSPOSE_WORLD_MATRIX, zonetool::h1::CONST_SRC_CODE_PREV_FRAME_TRANSPOSE_WORLD_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_PREV_FRAME_INVERSE_TRANSPOSE_WORLD_MATRIX, zonetool::h1::CONST_SRC_CODE_PREV_FRAME_INVERSE_TRANSPOSE_WORLD_MATRIX},
				{zonetool::h2::CONST_SRC_CODE_WORLD_MATRIX0, zonetool::h1::CONST_SRC_CODE_WORLD_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_WORLD_MATRIX0, zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_WORLD_MATRIX0, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_MATRIX0, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_WORLD_VIEW_MATRIX0, zonetool::h1::CONST_SRC_CODE_WORLD_VIEW_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_WORLD_VIEW_MATRIX0, zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_VIEW_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_MATRIX0, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_MATRIX0, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_WORLD_VIEW_PROJECTION_MATRIX0, zonetool::h1::CONST_SRC_CODE_WORLD_VIEW_PROJECTION_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_WORLD_VIEW_PROJECTION_MATRIX0, zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_VIEW_PROJECTION_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX0, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX0, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX0},
				{zonetool::h2::CONST_SRC_CODE_WORLD_MATRIX1, zonetool::h1::CONST_SRC_CODE_WORLD_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_WORLD_MATRIX1, zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_WORLD_MATRIX1, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_MATRIX1, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_WORLD_VIEW_MATRIX1, zonetool::h1::CONST_SRC_CODE_WORLD_VIEW_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_WORLD_VIEW_MATRIX1, zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_VIEW_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_MATRIX1, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_MATRIX1, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_WORLD_VIEW_PROJECTION_MATRIX1, zonetool::h1::CONST_SRC_CODE_WORLD_VIEW_PROJECTION_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_WORLD_VIEW_PROJECTION_MATRIX1, zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_VIEW_PROJECTION_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX1, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX1, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX1},
				{zonetool::h2::CONST_SRC_CODE_WORLD_MATRIX2, zonetool::h1::CONST_SRC_CODE_WORLD_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_WORLD_MATRIX2, zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_WORLD_MATRIX2, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_MATRIX2, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_WORLD_VIEW_MATRIX2, zonetool::h1::CONST_SRC_CODE_WORLD_VIEW_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_WORLD_VIEW_MATRIX2, zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_VIEW_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_MATRIX2, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_MATRIX2, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_WORLD_VIEW_PROJECTION_MATRIX2, zonetool::h1::CONST_SRC_CODE_WORLD_VIEW_PROJECTION_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_WORLD_VIEW_PROJECTION_MATRIX2, zonetool::h1::CONST_SRC_CODE_INVERSE_WORLD_VIEW_PROJECTION_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX2, zonetool::h1::CONST_SRC_CODE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX2},
				{zonetool::h2::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX2, zonetool::h1::CONST_SRC_CODE_INVERSE_TRANSPOSE_WORLD_VIEW_PROJECTION_MATRIX2},
			};

			unsigned short convert_code_const(unsigned short index)
			{
				const auto iter = mapped_code_consts.find(index);
				if (iter == mapped_code_consts.end())
				{
					ZONETOOL_ERROR("Couldn't map code const %i", index);
					return zonetool::h1::CONST_SRC_NONE;
				}

				return iter->second;
			}

			unsigned short convert_dest(unsigned short dest)
			{
				if (dest >= 0x7F)
				{
					return dest;
				}

				if (dest >= 65)
				{
					return dest - 3;
				}

				if (dest >= 15)
				{
					return dest - 1;
				}

				return dest;
			}

			zonetool::h1::MaterialShaderArgument* convert_shader_arguments(zonetool::h2::MaterialPass* pass, utils::memory::allocator& allocator)
			{
				const auto arg_count = pass->perPrimArgCount + pass->perObjArgCount + pass->stableArgCount;
				const auto converted_args = allocator.allocate_array<zonetool::h1::MaterialShaderArgument>(arg_count);
				std::memcpy(converted_args, pass->args, sizeof(zonetool::h2::MaterialShaderArgument) * arg_count);

				for (auto i = 0; i < arg_count; i++)
				{
					if (converted_args[i].type != zonetool::h1::MTL_ARG_CODE_CONST)
					{
						continue;
					}

					//if (i >= pass->perPrimArgCount + pass->perObjArgCount)
					{
						converted_args[i].dest = convert_dest(converted_args[i].dest);
					}

					converted_args[i].u.codeConst.index = convert_code_const(converted_args[i].u.codeConst.index);
				}

				return converted_args;
			}

			unsigned char* convert_shader_program(unsigned char* program, unsigned int program_size,
				utils::memory::allocator& allocator)
			{
				if (program == nullptr)
				{
					return program;
				}

				const auto new_program = allocator.allocate_array<unsigned char>(program_size);
				std::memcpy(new_program, program, program_size);

				const auto offsets = ::shader::get_dest_reference_offsets(new_program, program_size);
				for (const auto& offset : offsets)
				{
					const auto dest = reinterpret_cast<unsigned int*>(new_program + offset);
					*dest = static_cast<unsigned int>(convert_dest(static_cast<unsigned short>(*dest)));
				}

				const auto checksum = ::shader::generate_checksum(new_program, program_size);
				const auto header = reinterpret_cast<::shader::dx11_shader_header*>(new_program);
				std::memcpy(header->checksum, &checksum, sizeof(::shader::shader_checksum));

				return new_program;
			}

			template <shader_type ShaderType, typename T, typename S>
			T* convert_shader(S* source, utils::memory::allocator& allocator)
			{
				const auto new_shader = allocator.allocate<T>();
				std::memcpy(new_shader, source, sizeof(S));

				if constexpr (ShaderType != none)
				{
					new_shader->prog.loadDef.program =
						convert_shader_program(new_shader->prog.loadDef.program, new_shader->prog.loadDef.programSize, allocator);

					if constexpr (ShaderType == pixelshader || ShaderType == vertexshader)
					{
						new_shader->prog.loadDef.microCodeCrc = ::shader::calc_crc32(
							new_shader->prog.loadDef.program, new_shader->prog.loadDef.programSize);
					}
				}

				new_shader->name = allocator.duplicate_string(game::add_source_postfix(new_shader->name, game::h2));
				return new_shader;
			}

			template <shader_type ShaderType, typename T, typename S>
			void convert_shader(T** target, S* source, utils::memory::allocator& allocator)
			{
				if (source == nullptr)
				{
					return;
				}

				*target = convert_shader<ShaderType, T, S>(source, allocator);
			}

			zonetool::h1::MaterialTechnique* convert(zonetool::h2::MaterialTechnique* technique, utils::memory::allocator& allocator)
			{
				if (technique == nullptr)
				{
					return nullptr;
				}

				const auto size = sizeof(zonetool::h1::MaterialTechniqueHeader) +
					sizeof(zonetool::h1::MaterialPass) * technique->hdr.passCount;
				const auto new_technique = reinterpret_cast<zonetool::h1::MaterialTechnique*>(allocator.allocate_array<char>(size));
				std::memcpy(new_technique, technique, size);

				new_technique->hdr.name = allocator.duplicate_string(game::add_source_postfix(technique->hdr.name, game::h2));
				new_technique->hdr.flags = technique->hdr.flags;
				new_technique->hdr.passCount = technique->hdr.passCount;

				for (auto i = 0u; i < technique->hdr.passCount; i++)
				{
					const auto new_pass = &new_technique->passArray[i];
					const auto pass = &technique->passArray[i];

					std::memcpy(new_pass, pass, sizeof(zonetool::h2::MaterialPass));

					new_pass->stableArgSize += 16;

					convert_shader<shader_type::none>(&new_pass->vertexShader, pass->vertexShader, allocator);
					convert_shader<shader_type::none>(&new_pass->vertexDecl, pass->vertexDecl, allocator);
					convert_shader<shader_type::none>(&new_pass->hullShader, pass->hullShader, allocator);
					convert_shader<shader_type::none>(&new_pass->domainShader, pass->domainShader, allocator);
					convert_shader<shader_type::none>(&new_pass->pixelShader, pass->pixelShader, allocator);

					new_pass->args = convert_shader_arguments(pass, allocator);
				}

				return new_technique;
			}

			zonetool::h1::MaterialTechniqueSet* convert(zonetool::h2::MaterialTechniqueSet* asset, utils::memory::allocator& allocator)
			{
				const auto new_asset = allocator.allocate<zonetool::h1::MaterialTechniqueSet>();

				new_asset->name = allocator.duplicate_string(game::add_source_postfix(asset->name, game::h2));
				COPY_VALUE(flags);
				COPY_VALUE(worldVertFormat);
				COPY_VALUE(preDisplacementOnlyCount);

				const auto remapped_techniques = remap(asset->techniques, allocator);
				for (auto i = 0; i < zonetool::h1::MaterialTechniqueType::TECHNIQUE_COUNT; i++)
				{
					new_asset->techniques[i] = convert(remapped_techniques[i], allocator);
				}

				return new_asset;
			}

			void dump(zonetool::h2::ComputeShader* asset)
			{
				utils::memory::allocator allocator;
				const auto converted_shader = convert_shader<shader_type::computeshader, 
					zonetool::h1::ComputeShader>(asset, allocator);
				zonetool::h1::compute_shader::dump(converted_shader);
			}

			void dump(zonetool::h2::MaterialVertexShader* asset)
			{
				utils::memory::allocator allocator;
				const auto converted_shader = convert_shader<shader_type::vertexshader, 
					zonetool::h1::MaterialVertexShader>(asset, allocator);
				zonetool::h1::vertex_shader::dump(converted_shader);
			}

			void dump(zonetool::h2::MaterialHullShader* asset)
			{
				utils::memory::allocator allocator;
				const auto converted_shader = convert_shader<shader_type::hullshader, 
					zonetool::h1::MaterialHullShader>(asset, allocator);
				zonetool::h1::hull_shader::dump(converted_shader);
			}

			void dump(zonetool::h2::MaterialDomainShader* asset)
			{
				utils::memory::allocator allocator;
				const auto converted_shader = convert_shader<shader_type::domainshader, 
					zonetool::h1::MaterialDomainShader>(asset, allocator);
				zonetool::h1::domain_shader::dump(converted_shader);
			}

			void dump(zonetool::h2::MaterialPixelShader* asset)
			{
				utils::memory::allocator allocator;
				const auto converted_shader = convert_shader<shader_type::pixelshader, 
					zonetool::h1::MaterialPixelShader>(asset, allocator);
				zonetool::h1::pixel_shader::dump(converted_shader);
			}

			void dump(zonetool::h2::MaterialTechniqueSet* asset)
			{
				utils::memory::allocator allocator;
				const auto converted_asset = convert(asset, allocator);
				zonetool::h1::techset::dump(converted_asset);
			}
		}
	}
}
